VideoAPI/Video.API/ConfigureServicesExtensions.cs, VideoAPI/Video.API/KinlyApiTokenDelegatingHandler.cs, VideoAPI/Video.API/Startup.cs, VideoAPI/VideoApi.UnitTests/CustomJwtToken/HashGeneratorTests.cs
=> adding authorisation header for kinly endpoint calls

VideoAPI/Testing.Common/Assertions/AssertConferenceDetailsResponse.cs, VideoAPI/Video.API/Mappings/ConferenceToDetailsResponseMapper.cs, VideoAPI/Video.API/Mappings/ConferenceToSummaryResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceSummaryResponse.cs, VideoAPI/VideoApi.Contract/Responses/ParticipantDetailsResponse.cs, VideoAPI/VideoApi.DAL/Mappings/ConferenceMap.cs, VideoAPI/VideoApi.DAL/Migrations/20190624115332_AddConferenceClosedTime.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20190624115332_AddConferenceClosedTime.cs, VideoAPI/VideoApi.Domain/Conference.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateConferenceStatusCommandTests.cs, VideoAPI/VideoApi.UnitTests/Domain/Conference/UpdateConferenceStatusTests.cs
[VIH-4195](https://tools.hmcts.net/jira/browse/VIH-4195)
Add conference closed time property. This gets set when the conference status is updated to the closed state
```
[ ] Yes
[x] No
```
=> add the closed time to the conference

VideoAPI/Video.API/Controllers/HealthCheckController.cs
[VIH-4690](https://tools.hmcts.net/jira/browse/VIH-4690)
health endpoint has AllowAnonymous filter applied
```
[ ] Yes
[x] No
```
=> allow health endpoint to be reached without auth

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/Video.API/Validations/UpdateParticipantRequestValidation.cs, VideoAPI/VideoApi.Contract/Requests/UpdateParticipantRequest.cs, VideoAPI/VideoApi.DAL/Commands/UpdateConferenceDetailsCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoAPI/VideoApi.IntegrationTests/Api/Participants.feature, VideoAPI/VideoApi.IntegrationTests/Api/Participants.feature.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantDetailsCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ParticipantSteps.cs, VideoAPI/VideoApi.UnitTests/Validation/UpdateParticipantRequestValidationTests.cs
=> Added update participant details endpoint, command, tests

VideoAPI/Video.API/Controllers/CallbackController.cs, VideoAPI/Video.API/Extensions/ExceptionMiddleware.cs, VideoAPI/Video.API/Startup.cs, VideoAPI/VideoApi.AcceptanceTests/Contexts/TestContext.cs, VideoAPI/VideoApi.AcceptanceTests/Hooks/ApiHooks.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/CallbackSteps.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/TasksSteps.cs, VideoAPI/VideoApi.Common/Security/CustomToken/CustomJwtTokenProvider.cs, VideoAPI/VideoApi.Common/Security/CustomToken/CustomTokenSettings.cs, VideoAPI/VideoApi.Common/Security/CustomToken/ICustomJwtTokenProvider.cs, VideoAPI/VideoApi.IntegrationTests/Contexts/ApiTestContext.cs, VideoAPI/VideoApi.IntegrationTests/Hooks/ApiHooks.cs, VideoAPI/VideoApi.IntegrationTests/Steps/CallbacksSteps.cs, azure-pipelines.yml
=> Added token authentication on callback endpoint

VideoAPI/Video.API/Mappings/ParticipantToSummaryResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ParticipantSummaryResponse.cs, VideoAPI/VideoApi.UnitTests/Mappings/ParticipantToSummaryResponseMapperTests.cs
[VIH-4607](https://tools.hmcts.net/jira/browse/VIH-4607)
expose the case group to safely filter and display participants in clerk hearing list
```
[ ] Yes
[ ] No
```
=> expose case group for summary

VideoAPI/VideoApi.Domain/Enums/EventType.cs, VideoAPI/VideoApi.Events/Handlers/SuspendEventHandler.cs, VideoAPI/VideoApi.UnitTests/Events/EventHandlerTestBase.cs, VideoAPI/VideoApi.UnitTests/Events/SuspendEventHandlerTests.cs
Added suspend event handler
```
[ ] Yes
[x ] No
```
=> Added susped event handler

VideoAPI/VideoApi.UnitTests/CustomJwtToken/CustomJwtTokenProviderTests.cs
=> Cleaning up tests

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConsultationController.cs, VideoAPI/Video.API/Validations/LeaveConsultationRequestValidation.cs, VideoAPI/VideoApi.Contract/Requests/LeaveConsultationRequest.cs, VideoAPI/VideoApi.IntegrationTests/Api/Consultations.feature, VideoAPI/VideoApi.IntegrationTests/Steps/ConsultationSteps.cs, VideoAPI/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Validation/LeaveConsultationRequestValidationTests.cs
[VIH-4234](https://tools.hmcts.net/jira/browse/VIH-4234)
Implement endpoint to leave a consultation, returning participants back to the waiting room
```
[ ] Yes
[x] No
```
=> Add endpoint to leave a consultation

VideoAPI/Video.API/Controllers/ConsultationController.cs, VideoAPI/VideoApi.Contract/Requests/ConsultationRequest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/HandleConsultationRequestTests.cs
- Add 'Cancelled' answer as a response to handling consultation requests
```
[ ] Yes
[x] No
```
=> Add consultation answer 'cancelled'

VideoAPI/Video.API/ConfigureServicesExtensions.cs
[VIH-4134](https://tools.hmcts.net/jira/browse/VIH-4134)
Add snake casing strategy to kinly api serialiser settings
```
[ ] Yes
[x] No
```
=> Update kinly client to use snake casing

VideoAPI/Video.API/Program.cs, VideoAPI/Video.API/Startup.cs, VideoAPI/VideoApi.Common/Security/CustomToken/CustomJwtTokenHandler.cs, VideoAPI/VideoApi.Common/Security/CustomToken/CustomJwtTokenProvider.cs
[VIH-4134](https://tools.hmcts.net/jira/browse/VIH-4134)
Remove audience from JWT made for kinly api
```
[ ] Yes
[x] No
```
=> remove audience in token for kinly api

VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs
[VIH-4884](https://tools.hmcts.net/jira/browse/VIH-4884)
Filter for conferences created by automated tests before cleaning
```
[ ] Yes
[x] No
```
=> filter for automated tests before clearing up conferences

VideoAPI/VideoApi.Common/VideoApi.Common.csproj, VideoAPI/VideoApi.Events/VideoApi.Events.csproj
[VIH-4920](https://tools.hmcts.net/jira/browse/VIH-4920)
Updated packages with security issues
```
[ ] Yes
[x] No
```
=> Updated packages with security issues

VideoAPI/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoAPI/VideoApi.UnitTests/Events/TransferEventHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-4922
updated transfer event to reflect move from consultation to in hearing
```
[ ] Yes
[x] No
```
=> Transfer fix for Consultation to In hearing

VideoAPI/Testing.Common/Helper/Builders/Api/BookNewConferenceRequestBuilder.cs, VideoAPI/Testing.Common/Helper/Builders/Api/ParticipantRequestBuilder.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/CallbackSteps.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ParticipantsSteps.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesForTodayByUsernameQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ParticipantSteps.cs
Appending names of fake conferences and users to make it easier to cleanup left behind data
```
[ ] Yes
[X] No
```
=> Test data cleanup

VideoAPI/VideoApi.AcceptanceTests/Hooks/ApiHooks.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/CreateConferenceCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/CheckConferenceOpenQueryTests.cs
Removed final left behind data
```
[ ] Yes
[X] No
```
=> Removed final data left behind by tests

VideoAPI/VideoApi.DAL/Commands/RemoveConferenceCommand.cs
n/a
remove additional data not removed when deleting conferences
```
[ ] Yes
[x] No
```
=> Remove the test call data and events for a conference when deleting

VideoAPI/Testing.Common/Assertions/AssertConferenceSummaryResponse.cs, VideoAPI/Video.API/Mappings/ConferenceToSummaryResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceSummaryResponse.cs
=> Revert "Include the hearing id in the summary response"

VideoAPI/VideoApi.AcceptanceTests/Hooks/ApiHooks.cs
Added a config check for the pipelines.
```
[ ] Yes
[X] No
```
=> Added verification to prove secrets are correct

VideoAPI/VideoApi.AcceptanceTests/Features/Events.feature, VideoAPI/VideoApi.AcceptanceTests/Steps/EventsSteps.cs
- Changed the test name
- Changed the even type
```
[ ] Yes
[X] No
```
=> Updated event test

VideoAPI/VideoApi.Common/Security/CustomToken/CustomJwtTokenProvider.cs
No Jira
added Issued At time to token descriptor
```
[ ] Yes
[x] No
```
=> updated token generator, added IssueAt datetime to the token descriptor

azure-pipelines.yml
build on pushes to release/*
```
[X] Yes
[ ] No
```
=> build on pushes to release/*

VideoAPI/Video.API/Controllers/VideoEventsController.cs
https://tools.hmcts.net/jira/browse/VIH-5225
logging to app insights
```
[ ] Yes
[x] No
```
=> logging event info to application insights

VideoAPI/Testing.Common/Assertions/AssertConferenceDetailsResponse.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Mappings/ConferenceToDetailsResponseMapper.cs, VideoAPI/Video.API/Mappings/ConferenceToSummaryResponseMapper.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.Contract/Requests/BookNewConferenceRequest.cs, VideoAPI/VideoApi.Contract/Requests/UpdateConferenceRequest.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceSummaryResponse.cs, VideoAPI/VideoApi.DAL/Commands/CreateConferenceCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateConferenceDetailsCommand.cs, VideoAPI/VideoApi.DAL/Migrations/20200110151602_AddHearingVenueName.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200110151602_AddHearingVenueName.cs, VideoAPI/VideoApi.Domain/Conference.cs, VideoAPI/VideoApi.IntegrationTests/Api/Conferences.feature, VideoAPI/VideoApi.IntegrationTests/Database/Commands/CreateConferenceCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateConferenceDetailsCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.Services/Clients/UserApiClient.cs, VideoAPI/VideoApi.UnitTests/Controllers/ConferenceControllerTest.cs
https://tools.hmcts.net/jira/browse/VIH-5452
```
[ ] Yes
[ ] No
```
=> VIH-5452: Adding Hearing Venue Name

VideoAPI/Video.API/Mappings/ConferenceToSummaryResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceSummaryResponse.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceToSummaryMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-5503
Add property list of tasks to ConferenceToSummaryResponse
```
[ X] Yes
[ ] No
```
=> VIH-5503 Add to conference response the list of active tasks

VideoAPI/Video.API/ConfigureServicesExtensions.cs
[VIH-5479](https://tools.hmcts.net/jira/browse/VIH-5479)
* Bug Fixes
```
[ ] Yes
[x] No
```
=> Fix Kinly Client Registration to set correct  base url

VideoAPI/VideoApi.Domain/Enums/EventType.cs, VideoAPI/VideoApi.Events/Handlers/JudgeUnavailableEventHandler.cs, VideoAPI/VideoApi.UnitTests/Events/JudgeUnavailableEventHandlerTest.cs
https://tools.hmcts.net/jira/browse/VIH-5431
Added status judge unavailable
```
[X ] Yes
[ ] No
```
=> VIH-5431 Added status  judge unavailable

VideoAPI/VideoApi.DAL/Mappings/ConferenceMap.cs, VideoAPI/VideoApi.DAL/Mappings/MessageMap.cs, VideoAPI/VideoApi.DAL/Migrations/20200205131422_AddMessage.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200205131422_AddMessage.cs, VideoAPI/VideoApi.DAL/VideoApiDbContext.cs, VideoAPI/VideoApi.Domain/Conference.cs, VideoAPI/VideoApi.Domain/Message.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceToSummaryMapperTests.cs
Task : https://tools.hmcts.net/jira/browse/VIH-5488
Main Story : https://tools.hmcts.net/jira/browse/VIH-5515
Created a new table 'Message' to store instant messages
```
[ ] Yes
[x ] No
```
=> Task VIH-5488 : Created a new table Message to store instant messages

VideoAPI/VideoApi.Events/Handlers/LeaveEventHandler.cs, VideoAPI/VideoApi.UnitTests/Events/LeaveEventHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-5546
If participant is judge then leave event set participant status to not signed in
```
[X ] Yes
[ ] No
```
=> VIH-5546 Judge leave event

VideoAPI/Testing.Common/Assertions/AssertConferenceDetailsResponse.cs, VideoAPI/Video.API/appsettings.Development.json, VideoAPI/VideoApi.DAL/Queries/GetConferencesTodayQuery.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs
[VIH-5594](https://tools.hmcts.net/jira/browse/VIH-5594)
Add assertions on participant list to ensure particicipants exist in query
```
[ ] Yes
[x] No
```
=> [VIH-5594] bugfix optimise queries

VideoAPI/Testing.Common/Assertions/AssertSerializableError.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Testing.Common/Testing.Common.csproj, VideoAPI/VideoApi.UnitTests/.config/dotnet-tools.json, VideoAPI/VideoApi.UnitTests/Controllers/Conference/BookNewConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/CloseConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/GetConferenceByHearingRefIdTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/GetConferenceDetailsByIdTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/GetConferencesForUsernameTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/UpdateConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/ConsultationControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/HandleConsultationRequestTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/LeavePrivateConsultationTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/RespondToAdminConsultationRequestTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Message/MessageControllerTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/AddParticipantsToConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetTestCallResultForParticipantTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetTestCallResultForRepresentativeTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/ParticipantsControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/RemoveParticipantFromConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/UpdateParticipantDetailsTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Tasks/TasksControllerTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/ParticipantToSummaryResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Middleware/ExceptionMiddlewareTests.cs, VideoAPI/VideoApi.UnitTests/Validation/AdminConsultationRequestValidationTests.cs, VideoAPI/VideoApi.UnitTests/stryker-config.json
https://tools.hmcts.net/jira/browse/VIH-5543
- Installed Stryker and added stryker settings to UnitTests
- Added and updated unit tests to cover mutation testing
```
[ ] Yes
[x] No
```
=> Installed Stryker and added stryker settings to UnitTests

VideoAPI/VideoApi.DAL/Commands/SaveMonitoringCommand.cs, VideoAPI/VideoApi.DAL/Mappings/MonitoringMap.cs, VideoAPI/VideoApi.DAL/Migrations/20200221142418_AddMonitoring.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200221142418_AddMonitoring.cs, VideoAPI/VideoApi.DAL/VideoApiDbContext.cs, VideoAPI/VideoApi.Domain/Monitoring.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/SaveMonitoringCommandTest.cs
https://tools.hmcts.net/jira/browse/VIH-5596
```
[ ] Yes
[ ] No
```
=> VIH-5596: Adding the Monitoring table migration and classes

.githooks/pre-commit, README.md
https://tools.hmcts.net/jira/browse/VIH-5605
Added git hook to control branch naming, update Readme file
```
[X ] Yes
[ ] No
```
=> VIH-5605 added pre-commit hook to control new git branch name

VideoAPI/Video.API/Controllers/ParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-5566
```
[ ] Yes
[ ] No
```
=> VIH-5566: Change ProducesResponseType to be an IEnumerable

.githooks/pre-commit, .githooks/prepare-commit-msg, README.md
https://tools.hmcts.net/jira/browse/VIH-5605
Added git hook prepare-commit-message to validate format of commit description.
```
[ X] Yes
[ ] No
```
=> feature/VIH-5605 : added pre commit message hook

VideoAPI/Testing.Common/Assertions/AssertParticipantSummaryResponse.cs, VideoAPI/Video.API/Mappings/ParticipantToSummaryResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ParticipantSummaryResponse.cs
https://tools.hmcts.net/jira/browse/VIH-5566
```
[ ] Yes
[ ] No
```
=> VIH-5566: Adding Id to ParticipantSummaryResponse.cs

VideoAPI/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoAPI/VideoApi.DAL/Queries/CheckConferenceOpenQuery.cs, VideoAPI/VideoApi.Events/Handlers/DisconnectedEventHandler.cs, VideoAPI/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConsultationSteps.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs
https://tools.hmcts.net/jira/browse/VIH-5696
```
[ ] Yes
[ ] No
```
=> VIH-5696: ConfigureAwait(false) removal

VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Controllers/InstantMessageController.cs, VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/Video.API/Controllers/SelfTestController.cs, VideoAPI/Video.API/Controllers/TasksController.cs, VideoAPI/Video.API/Mappings/ConferenceToDetailsResponseMapper.cs, VideoAPI/Video.API/Mappings/ConferenceToExpiredConferenceMapper.cs, VideoAPI/Video.API/Mappings/ConferenceToSummaryResponseMapper.cs, VideoAPI/Video.API/Mappings/ConferenceToclosedConferenceMapper.cs, VideoAPI/Video.API/Mappings/InstantMessageToResponseMapper.cs, VideoAPI/Video.API/Mappings/MeetingRoomToResponseMapper.cs, VideoAPI/Video.API/Mappings/ParticipantToDetailsResponseMapper.cs, VideoAPI/Video.API/Mappings/ParticipantToSummaryResponseMapper.cs, VideoAPI/Video.API/Mappings/PexipConfigurationMapper.cs, VideoAPI/Video.API/Mappings/TaskCallResultResponseMapper.cs, VideoAPI/Video.API/Mappings/TaskToResponseMapper.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesForTodayByUsernameQueryTests.cs, VideoAPI/VideoApi.UnitTests/Events/TransferEventHandlerTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceToSummaryMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/MeetingRoomToResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/ParticipantToSummaryResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/SelfTestResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/TaskCallResultResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/TaskToResponseMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-5695
```
[ ] Yes
[ ] No
```
=> VIH-5695: Mappers Static

VideoAPI/Testing.Common/Assertions/AssertConferenceForAdminResponse.cs, VideoAPI/Testing.Common/Configuration/Test.cs, VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Controllers/ConsultationController.cs, VideoAPI/Video.API/Controllers/InstantMessageController.cs, VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/Video.API/Controllers/TasksController.cs, VideoAPI/Video.API/Mappings/ConferenceForAdminResponseMapper.cs, VideoAPI/VideoApi.AcceptanceTests/Hooks/ConfigHooks.cs, VideoAPI/VideoApi.AcceptanceTests/Hooks/RemoveDataHooks.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceForAdminResponse.cs, VideoAPI/VideoApi.DAL/Commands/RemoveParticipantsFromConferenceCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoAPI/VideoApi.DAL/Queries/GetConferencesTodayForAdminQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesTodayForAdminQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Hooks/RemoveDataHooks.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/RespondToAdminConsultationRequestTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/AddParticipantsToConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetParticipantHeartbeatTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetTestCallResultForParticipantTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetTestCallResultForRepresentativeTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/ParticipantsControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/RemoveParticipantFromConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/SaveParticipantHeartbeatTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/UpdateParticipantDetailsTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceForAdminResponseMapperTests.cs
VIH-5733
Change get conference today to be VH officer specific
Reduce calls to get conference query
```
[x] Yes
[] No
```
=> VIH-5733 Change get conferences today to be VH specific

VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Controllers/InstantMessageController.cs, VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/VideoApi.DAL/Commands/AddInstantMessageCommand.cs, VideoAPI/VideoApi.DAL/Commands/AddParticipantsToConferenceCommand.cs, VideoAPI/VideoApi.DAL/Commands/AddTaskCommand.cs, VideoAPI/VideoApi.DAL/Commands/CloseConferenceCommand.cs, VideoAPI/VideoApi.DAL/Commands/RemoveConferenceCommand.cs, VideoAPI/VideoApi.DAL/Commands/RemoveInstantMessagesForConferenceCommand.cs, VideoAPI/VideoApi.DAL/Commands/RemoveParticipantsFromConferenceCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateConferenceStatusCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateMeetingRoomCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateParticipantStatusCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateSelfTestCallResultCommand.cs, VideoAPI/VideoApi.Events/Handlers/DisconnectedEventHandler.cs, VideoAPI/VideoApi.Events/Handlers/MediaPermissionDeniedEventHandler.cs, VideoAPI/VideoApi.Events/Handlers/SelfTestFailedEventhandler.cs, VideoAPI/VideoApi.Events/Handlers/SuspendEventHandler.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/RemoveInstantMessagesForConferenceCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantStatusAndRoomCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantStatusCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Features/Participants.feature, VideoAPI/VideoApi.UnitTests/Controllers/InstantMessage/InstantMessageControllerTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/AddParticipantsToConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/ParticipantsControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/SaveParticipantHeartbeatTests.cs
https://tools.hmcts.net/jira/browse/VIH-5744
```
[ ] Yes
[ ] No
```
=> VIH-5744 Optimise commands

VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/VideoApi.IntegrationTests/Features/Participants.feature, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetParticipantHeartbeatTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/SaveParticipantHeartbeatTests.cs
https://tools.hmcts.net/jira/browse/VIH-5744
```
[ ] Yes
[ ] No
```
=> VIH-5744 optimise_heartbeat

VideoAPI/Video.API/ConfigureServicesExtensions.cs, VideoAPI/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.Services/RoomReservationService.cs, VideoAPI/VideoApi.UnitTests/Events/EventHandlerTestBase.cs, VideoAPI/VideoApi.UnitTests/Events/TransferEventHandlerTests.cs, VideoAPI/VideoApi.UnitTests/Services/KinlyPlatformServiceTests.cs, VideoAPI/VideoApi.UnitTests/Services/RoomReservationServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-5492
```
[ x] Yes
[ ] No
```
=> VIH-5492 Private consultation Bug fix

VideoAPI/Video.API/Startup.cs, VideoAPI/Video.API/Telemetry/SuccessfulDependencyProcessor.cs
https://tools.hmcts.net/jira/browse/VIH-5471
Filter out known errors such as 404
```
[ ] Yes
[ ] No
```
=> VIH-5471 Filter out known errors

VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.UnitTests/Services/KinlyPlatformServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-5455
```
[ ] Yes
[ ] No
```
=> VIH-5455 Pass audio options to kinly

VideoAPI/VideoApi.Services/AzureMediaAudioPlatformService.cs
…recording is true
https://tools.hmcts.net/jira/browse/VIH-5455
```
[ ] Yes
[ ] No
```
=> VIH-5455 Fix the empty string passed to kinly if audio

VideoAPI/Video.API/Controllers/ConsultationController.cs, VideoAPI/VideoApi.IntegrationTests/Features/Consultations/LeavePrivateConsultation.feature, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/LeavePrivateConsultationTests.cs
https://tools.hmcts.net/jira/browse/VIH-5797
feature/VIH-5797 : Removed bad request for a known behaviour upon leaving private consultation
```
[ ] Yes
[ ] No
```
=> VIH-5797 Removed bad request for a known behaviour upon leaving private consultation

VideoAPI/Video.API/Mappings/ConferenceToDetailsResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-5811
Add audio recording options to response for endpoint GetConferenceDetailsById
```
[ X] Yes
[ ] No
```
=> VIH-5811 add Audio recording option to response

VideoAPI/Video.API/Mappings/ConferenceForIndividualResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceForIndividualResponse.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceForIndividualResponseMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-5844
- added Conference State and Closed Date time to the individual response model
```
[ ] Yes
[x] No
```
=> VIH-5844 Video_Web___Participants_are_able_to_access_a_closed_hearing_after_30_minutes

VideoAPI/Testing.Common/Testing.Common.csproj, VideoAPI/VideoApi.AcceptanceTests/VideoApi.AcceptanceTests.csproj, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesTodayForAdminQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoAPI/VideoApi.IntegrationTests/VideoApi.IntegrationTests.csproj, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/ConsultationControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/LeavePrivateConsultationTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/HealthChecks/HealthTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/ParticipantsControllerTestBase.cs
https://tools.hmcts.net/jira/browse/VIH-5858
- Updated acceptance tests nuget to remove OWASPZAPDotNetAPI reference
- Code clean up to remove warnings
```
[ ] Yes
[x] No
```
=> VIH-5858 Remove OWASPZAPDotNetAPI reference

VideoAPI/VideoApi.Services/Clients/WowzaHttpClient.cs
https://tools.hmcts.net/jira/browse/VIH-5780
```
[ ] Yes
[ ] No
```
=> VIH-5780 change application stream type

README.md, VideoAPI/VideoApi.Services/AudioPlatformService.cs, VideoAPI/VideoApi.Services/AudioPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Services/AudioPlatformServiceTest.cs
https://tools.hmcts.net/jira/browse/VIH-5780
```
[ ] Yes
[ ] No
```
=> VIH-5780 change ingest url format

VideoAPI/Testing.Common/Configuration/Test.cs, VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Mappings/ConferenceForJudgeResponseMapper.cs, VideoAPI/VideoApi.AcceptanceTests/Features/Conference.feature, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.Contract/Responses/JudgeInHearingResponse.cs, VideoAPI/VideoApi.DAL/Queries/GetJudgesInHearingsTodayQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetJudgesInHearingsTodayQueryTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/GetJudgesInHearingsTodayTests.cs
https://tools.hmcts.net/jira/browse/VIH-5827
```
[ ] Yes
[ ] No
```
=> VIH-5827 Add Judges in another hearing

VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/CloseConferenceTests.cs
https://tools.hmcts.net/jira/browse/VIH-5812
Delete audio recording application is added to close application action.
```
[X ] Yes
[ ] No
```
=> VIH-5812 Delete audio application in close hearing

VideoAPI/VideoApi.DAL/Migrations/20200429133402_CreateConferenceTableIdexes.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200429133402_CreateConferenceTableIdexes.cs
https://tools.hmcts.net/jira/browse/VIH-5916
```
[ ] Yes
[ ] No
```
=> VIH-5916 Add Indexes to the conference table

VideoAPI/VideoApi.DAL/Migrations/20200430155005_CreateConferenceTableIndexScheduledDate.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200430155005_CreateConferenceTableIndexScheduledDate.cs
https://tools.hmcts.net/jira/browse/VIH-5924
```
[ ] Yes
[ ] No
```
=> VIH-5924 Add index conference table ScheduledDateTime

VideoAPI/Video.API/Controllers/AudioRecordingController.cs
VIH-5780
```
[ ] Yes
[ ] No
```
=> VIH-5780 Fix swagger endpoints

VideoAPI/Video.API/Controllers/HealthCheckController.cs, VideoAPI/VideoApi.Contract/Responses/HealthCheckResponse.cs, VideoAPI/VideoApi.UnitTests/Controllers/HealthChecks/HealthTests.cs
https://tools.hmcts.net/jira/browse/VIH-5894
Added health check for wowza api
```
[X ] Yes
[ ] No
```
=> VIH-5894 health check for wowza engine

VideoAPI/VideoApi.Common/Configuration/WowzaConfiguration.cs, VideoAPI/VideoApi.Services/AudioPlatformService.cs, VideoAPI/VideoApi.Services/Clients/WowzaHttpClient.cs, VideoAPI/VideoApi.Services/Contracts/IWowzaHttpClient.cs, VideoAPI/VideoApi.UnitTests/Clients/WowzaHttpClientTest.cs, VideoAPI/VideoApi.UnitTests/Services/AudioPlatformServiceTest.cs
https://tools.hmcts.net/jira/browse/VIH-5945
- Added  feature to update application to add module and custom properties for azure storage
```
[ ] Yes
[x] No
```
=> VIH-5945 Update audio application to set module and properties

VideoAPI/Video.API/ConfigureServicesExtensions.cs, VideoAPI/Video.API/Controllers/AudioRecordingController.cs, VideoAPI/Video.API/Startup.cs, VideoAPI/Video.API/Video.API.csproj, VideoAPI/VideoApi.Common/Configuration/WowzaConfiguration.cs, VideoAPI/VideoApi.Contract/Responses/HearingAudioRecordingResponse.cs, VideoAPI/VideoApi.Services/AudioPlatformService.cs, VideoAPI/VideoApi.Services/AzureStorageService.cs, VideoAPI/VideoApi.Services/Contracts/IStorageService.cs, VideoAPI/VideoApi.Services/VideoApi.Services.csproj, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoAPI/VideoApi.UnitTests/Services/AzureStorageServiceTest.cs
https://tools.hmcts.net/jira/browse/VIH-5881
```
[ ] Yes
[ ] No
```
=> VIH-5881 Create Azure blob SAS

CODEOWNERS, VideoAPI/VideoApi.AcceptanceTests/Features/HealthCheck.feature, VideoAPI/VideoApi.AcceptanceTests/Steps/HealthCheckSteps.cs, VideoAPI/VideoApi.AcceptanceTests/VideoApi.AcceptanceTests.csproj, VideoAPI/VideoApi.IntegrationTests/Features/HealthCheck.feature, VideoAPI/VideoApi.IntegrationTests/Steps/HealthCheckSteps.cs
https://tools.hmcts.net/jira/browse/VIH-5894
- Added AC and Integration tests
```
[ ] Yes
[X] No
```
=> VIH-5894 Wowza Health Check Acceptance test

VideoAPI/Video.API/Controllers/HealthCheckController.cs, VideoAPI/VideoApi.Services/AudioPlatformService.cs, VideoAPI/VideoApi.Services/Clients/WowzaHttpClient.cs, VideoAPI/VideoApi.UnitTests/Clients/WowzaHttpClientTest.cs, VideoAPI/VideoApi.UnitTests/Services/AudioPlatformServiceTest.cs
https://tools.hmcts.net/jira/browse/VIH-5954
```
[ ] Yes
[ ] No
```
=> VIH-5954 Stop 404 getting logged as error for Wowza

VideoAPI/Video.API/Controllers/AudioRecordingController.cs
https://tools.hmcts.net/jira/browse/VIH-5881
```
[ ] Yes
[ ] No
```
=> VIH-5881 Change the file path for getting the file link

VideoAPI/Video.API/Controllers/HealthCheckController.cs
https://tools.hmcts.net/jira/browse/VIH-5954
```
[ ] Yes
[ ] No
```
=> VIH-5954 Change guid to empty guid

VideoAPI/VideoApi.Services/Clients/WowzaHttpClient.cs
…version the file
https://tools.hmcts.net/jira/browse/VIH-5331
```
[ ] Yes
[ ] No
```
=> VIH-5331 Tell wowza not to delete the original file

VideoAPI/VideoApi.Services/Clients/WowzaHttpClient.cs
=> VIH-5331 Fix mistake in wowza url

VideoAPI/Video.API/Controllers/AudioRecordingController.cs
https://tools.hmcts.net/jira/browse/VIH-5332
```
[ ] Yes
[ ] No
```
=> VIH-5332 Change the audio link SAS valid for 14days

VideoAPI/VideoApi.Services/AzureStorageService.cs
https://tools.hmcts.net/jira/browse/VIH-5331
```
[ ] Yes
[ ] No
```
=> VIH-5331 Change delegation time when getting token

VideoAPI/VideoApi.Services/Clients/WowzaHttpClient.cs, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-5977
```
[ ] Yes
[ ] No
```
=> VIH-5331 App setting for the integration tests in CD

VideoAPI/VideoApi.AcceptanceTests/Features/Events.feature, VideoAPI/VideoApi.Domain/Enums/EventType.cs, VideoAPI/VideoApi.Events/Handlers/ParticipantNotSignedInEventHandler.cs, VideoAPI/VideoApi.IntegrationTests/Features/Callbacks.feature, VideoAPI/VideoApi.UnitTests/Events/ParticipantNotSignedInEventHandlerTest.cs
https://tools.hmcts.net/jira/browse/VIH-5405
added event handler for Not Signed In participant status
```
[ X] Yes
[ ] No
```
=> VIH-5405 add event handler not signed in

VideoAPI/Video.API/Validations/ParticipantRequestValidation.cs, VideoAPI/Video.API/Validations/UpdateParticipantRequestValidation.cs, VideoAPI/VideoApi.DAL/Migrations/20200609104110_UpdateFirstLastNames.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ParticipantSteps.cs, VideoAPI/VideoApi.UnitTests/Validation/ParticipantRequestValidationTests.cs, VideoAPI/VideoApi.UnitTests/Validation/UpdateParticipantRequestValidationTests.cs
https://tools.hmcts.net/jira/browse/VIH-6083
Court room migration and Validation
```
[ ] Yes
[ x] No
```
=> VIH-6083 Court room migration and Validation

VideoAPI/Testing.Common/Configuration/Test.cs, VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Testing.Common/Helper/Builders/Api/BookNewConferenceRequestBuilder.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/VideoApi.AcceptanceTests/Features/Participants.feature, VideoAPI/VideoApi.AcceptanceTests/Hooks/ConfigHooks.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ParticipantsSteps.cs, VideoAPI/VideoApi.Contract/Responses/JudgeNameListResponse.cs, VideoAPI/VideoApi.DAL/Queries/GetDistinctJudgeListByFirstNameQuery.cs, VideoAPI/VideoApi.DAL/VideoApiDbContext.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetDistinctJudgeListByFirstNameQueryTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/GetJudgesInHearingsTodayTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/ConsultationControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetDistinctJudgeNamesTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/ParticipantsControllerTestBase.cs
https://tools.hmcts.net/jira/browse/VIH-6002
Get a list of distinct judge first names
```
[ ] Yes
[ x] No
```
=> VIH-6002 Get a list of distinct judge first names

VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Controllers/ConsultationController.cs, VideoAPI/Video.API/Controllers/InstantMessageController.cs, VideoAPI/Video.API/Controllers/TasksController.cs, VideoAPI/Video.API/Properties/serviceDependencies.json, VideoAPI/Video.API/Properties/serviceDependencies.local.json, VideoAPI/VideoApi.Contract/Requests/ConferenceForAdminRequest.cs, VideoAPI/VideoApi.DAL/Queries/GetConferencesTodayForAdminQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesTodayForAdminQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Features/ConferencesToday.feature, VideoAPI/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.UnitTests/.config/dotnet-tools.json, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/InstantMessage/InstantMessageControllerTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/RemoveParticipantFromConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Tasks/TasksControllerTests.cs, VideoAPI/VideoApi.UnitTests/stryker-config.json
Updates to the venue filter in VideoWeb
- updated query to filter conferences by user role judge and first name.
```
[ ] Yes
[x] No
```
=> VIH-6013 updates to the venue filter in video web

VideoAPI/Testing.Common/Configuration/Config.cs, VideoAPI/VideoApi.AcceptanceTests/Features/AudioRecording.feature, VideoAPI/VideoApi.AcceptanceTests/Hooks/ConfigHooks.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/AudioRecordingSteps.cs, VideoAPI/VideoApi.Common/Configuration/AudioRecordingTestIdConfiguration.cs, VideoAPI/VideoApi.Services/AudioPlatformServiceStub.cs
https://tools.hmcts.net/jira/browse/VIH-6026
Mocked audio hearing services
```
[ ] Yes
[x ] No
```
=> VIH-6026 Mocked audio hearing services

VideoAPI/Video.API/Mappings/ParticipantToSummaryResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ParticipantSummaryResponse.cs, VideoAPI/VideoApi.UnitTests/Mappings/ParticipantToSummaryResponseMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-5922
Added first and last name to participant response summary(for court rooms accounts filter)
```
[ X] Yes
[ ] No
```
=> VIH-5922 added first and last names to participant response

VideoAPI/Testing.Common/Assertions/AssertConferenceDetailsResponse.cs, VideoAPI/Testing.Common/Helper/Builders/Api/BookNewConferenceRequestBuilder.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/CreateConferenceCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateConferenceDetailsCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Features/Conferences.feature, VideoAPI/VideoApi.IntegrationTests/Helper/TestDataManager.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.Services.Generator/kinly-swagger.json, VideoAPI/VideoApi.Services/Clients/KinlyApiClient.cs, VideoAPI/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/BookNewConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/UpdateConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Services/KinlyPlatformServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-5785
=> VIH-5785 Update Kinly room audio on or off

VideoAPI/VideoApi.Services/AzureStorageService.cs
https://tools.hmcts.net/jira/browse/VIH-6119
=> VIH-6119 Change delegation to 7 days

VideoAPI/Testing.Common/Assertions/AssertConferenceForAdminResponse.cs
- Hotfix for StartTtime build issue
```
[ ] Yes
[X] No
```
=> VIH-5255 Hotfix for StartTime build issue

VideoAPI/Video.API/Controllers/AudioRecordingController.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.AcceptanceTests/Features/AudioRecording.feature, VideoAPI/VideoApi.AcceptanceTests/Steps/AudioRecordingSteps.cs, VideoAPI/VideoApi.IntegrationTests/Features/AudioRecording.feature, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/CloseConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs
https://tools.hmcts.net/jira/browse/VIH-6134
Check if audio file exists before delete audio app
```
[X ] Yes
[ ] No
```
=> VIH-6134 check audio file before delete

VideoAPI/VideoApi.DAL/Queries/GetConferencesForTodayByIndividualQuery.cs, VideoAPI/VideoApi.DAL/Queries/GetConferencesForTodayByJudgeQuery.cs, VideoAPI/VideoApi.DAL/Queries/GetConferencesTodayForAdminQuery.cs, VideoAPI/VideoApi.Domain/Conference.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesForTodayByIndividualQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesForTodayByJudgeQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesTodayForAdminQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceForAdminResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Services/Handlers/KinlyApiTokenDelegatingHandlerTest.cs
https://tools.hmcts.net/jira/browse/VIH-6168
=> VIH-6168 Change the queries to return the conferences only when they have meeting room assigned

VideoAPI/VideoApi.DAL/Queries/GetExpiredAudiorecordingConferencesQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetExpiredAudiorecordingConferencesQueryTests.cs
https://tools.hmcts.net/jira/browse/VIH-6226
Conference is expired if it's  more then 14 hours ago but not older then 38 hours
```
[ X] Yes
[ ] No
```
=> VIH-6226 expired conferences with audio

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.DAL/Commands/AnonymiseConferencesCommand.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/AnonymiseConferencesCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Features/Conferences.feature, VideoAPI/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs
https://tools.hmcts.net/jira/browse/VIH-1962
- added a new command to excute the sql script using ExecuteSqlRaw.
```
[ ] Yes
[x] No
```
=> VIH-1962 create automatic process to anonymise data and delete user accounts in line with gdpr

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceManagementController.cs, VideoAPI/VideoApi.IntegrationTests/Features/ConferenceManagement.feature, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceManagementSteps.cs, VideoAPI/VideoApi.Services.Generator/kinly-swagger.json, VideoAPI/VideoApi.Services/Clients/KinlyApiClient.cs, VideoAPI/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs
VIH-6177
* start or resume a video hearing via Kinly API
```
[ ] Yes
[x] No
```
=> VIH-6177 start or resume video hearing

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceManagementController.cs, VideoAPI/VideoApi.IntegrationTests/Features/ConferenceManagement.feature, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceManagementSteps.cs, VideoAPI/VideoApi.Services.Generator/kinly-swagger.json, VideoAPI/VideoApi.Services/Clients/KinlyApiClient.cs, VideoAPI/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Controllers/ConferenceManagement/PauseVideoHearingTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/ConferenceManagement/RequestTechnicalAssistanceTests.cs
VIH-6200
Request Technical Assistance
```
[ ] Yes
[x] No
```
=> VIH-6200 request technical assistance

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/VideoApi.AcceptanceTests/Features/Participants.feature, VideoAPI/VideoApi.AcceptanceTests/Steps/ParticipantsSteps.cs, VideoAPI/VideoApi.IntegrationTests/Features/Participants.feature, VideoAPI/VideoApi.IntegrationTests/Steps/ParticipantSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetParticipantsByConferenceIdTest.cs
https://tools.hmcts.net/jira/browse/VIH-6238
Endpoint to get participants for conference
```
[X ] Yes
[ ] No
```
=> VIH-6238 get participants for conference

VideoAPI/VideoApi.DAL/Queries/GetDistinctJudgeListByFirstNameQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetDistinctJudgeListByFirstNameQueryTests.cs
https://tools.hmcts.net/jira/browse/VIH-6347
- excluded anonymised users.
```
[ ] Yes
[x] No
```
=> VIH-6347 dont display any anonymised judge courtroom accounts in vho list

VideoAPI/VideoApi.Events/Handlers/LeaveEventHandler.cs, VideoAPI/VideoApi.UnitTests/Events/LeaveEventHandlerTests.cs
VIH-6173
* Judge leaving updates status to disconnected
```
[ ] Yes
[x] No
```
=> VIH-6173 Judge leaving updates status to disconnected

VideoAPI/Testing.Common/Assertions/AssertConferenceDetailsResponse.cs, VideoAPI/Testing.Common/Assertions/AssertParticipantSummaryResponse.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ParticipantBuilder.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/Video.API/Mappings/ParticipantToDetailsResponseMapper.cs, VideoAPI/Video.API/Mappings/ParticipantToSummaryResponseMapper.cs, VideoAPI/Video.API/Validations/ParticipantRequestValidation.cs, VideoAPI/VideoApi.Contract/Requests/ParticipantRequest.cs, VideoAPI/VideoApi.Contract/Requests/UpdateParticipantRequest.cs, VideoAPI/VideoApi.Contract/Responses/ParticipantDetailsResponse.cs, VideoAPI/VideoApi.Contract/Responses/ParticipantSummaryResponse.cs, VideoAPI/VideoApi.DAL/Commands/AnonymiseConferencesCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoAPI/VideoApi.DAL/Mappings/ParticipantMap.cs, VideoAPI/VideoApi.DAL/Migrations/20200811155212_AddContactInformation.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200811155212_AddContactInformation.cs, VideoAPI/VideoApi.Domain/Participant.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/AnonymiseConferencesCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantDetailsCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferencesTodayForAdminQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetParticipantsByConferenceIdTest.cs, VideoAPI/VideoApi.UnitTests/Domain/Conference/RemoveParticipantTests.cs, VideoAPI/VideoApi.UnitTests/Validation/ParticipantRequestValidationTests.cs
VIH-6043
* add contact telephone and email to Participant.cs
```
[x] Yes
[] No
```
=> VIH-6043 add contact telephone and email to Participant.cs

VideoAPI/VideoApi.DAL/Queries/GetJudgesInHearingsTodayQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetJudgesInHearingsTodayQueryTests.cs
VIH-6378
* checks for judges with available and inhearing status to determine who is in a hearing
```
[ ] Yes
[x] No
```
=> VIH-6378 bugfix update judge in hearing filter

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.DAL/Commands/RemoveHeartbeatsForConferencesCommand.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/RemoveHeartbeatsForConferencesCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Features/Conferences.feature, VideoAPI/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/RemoveHeartbeatsForConferencesTests.cs
https://tools.hmcts.net/jira/browse/VIH-6097
- added new function to clear heartbeats
```
[ ] Yes
[x] No
```
=> VIH-6097 Clear_down_hearing_heartbeat_data_after_2_weeks

CODEOWNERS, VideoAPI/Video.API/Controllers/AudioRecordingController.cs, VideoAPI/VideoApi.AcceptanceTests/Features/AudioRecording.feature, VideoAPI/VideoApi.AcceptanceTests/Steps/AudioRecordingSteps.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.IntegrationTests/Hooks/RemoveDataHooks.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/RemoveHeartbeatsForConferencesTests.cs
VIH-6398
* check conference has started before getting an audio recording link or deleting an audio application
```
[ ] Yes
[x] No
```
=> VIH-6398 check conference has started before audio calls

CODEOWNERS
- Fix for Codeowners file
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix codeowners

VideoAPI/VideoApi.DAL/Commands/SaveEventCommand.cs, VideoAPI/VideoApi.DAL/Mappings/EventMap.cs, VideoAPI/VideoApi.DAL/Migrations/20200825162507_AddEndpointFlagToEvent.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200825162507_AddEndpointFlagToEvent.cs, VideoAPI/VideoApi.Domain/Enums/EventType.cs, VideoAPI/VideoApi.Domain/Event.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/SaveEventCommandTests.cs
VIH-6360
* add endpoint flag to Event.cs with default value of false
```
[ ] Yes
[x] No
```
=> VIH-6360 add endpoint flag to Event.cs with default value of false

VideoAPI/Testing.Common/Assertions/AssertConferenceForIndividualResponse.cs, VideoAPI/Testing.Common/Assertions/AssertConferenceForJudgeResponse.cs, VideoAPI/Testing.Common/Assertions/AssertParticipantForJudgeResponse.cs, VideoAPI/Testing.Common/Configuration/Test.cs, VideoAPI/Video.API/Mappings/ConferenceForJudgeResponseMapper.cs, VideoAPI/VideoApi.AcceptanceTests/Features/Conference.feature, VideoAPI/VideoApi.AcceptanceTests/Hooks/ConfigHooks.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceForJudgeResponse.cs, VideoAPI/VideoApi.DAL/Queries/GetConferencesForTodayByJudgeQuery.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceForJudgeResponseMapperTests.cs
https://tools.hmcts.net/jira/browse/VIH-6327
add number of endpoints in hearing for judge, fix ac test
```
[X ] Yes
[ ] No
```
=> VIH-6427 add number of endpoints for judge

VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.DAL/Queries/GetConferenceByHearingRefIdQuery.cs, VideoAPI/VideoApi.DAL/Queries/GetNonClosedConferenceByHearingRefIdQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetConferenceByHearingRefIdQueryTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetNonClosedConferenceByHearingRefIdQueryTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/GetConferenceByHearingRefIdTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/UpdateConferenceTests.cs
VIH-6436
new get non-closed conference by hearing id
```
[ ] Yes
[x] No
```
=> VIH-6436 new get non-closed conference by hearing id

VideoAPI/Video.API/Controllers/EndpointsController.cs, VideoAPI/VideoApi.AcceptanceTests/Features/Events.feature, VideoAPI/VideoApi.AcceptanceTests/Steps/EndPointsSteps.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/EventsSteps.cs, VideoAPI/VideoApi.DAL/Commands/UpdateEndpointStatusCommand.cs, VideoAPI/VideoApi.DAL/Queries/GetConferenceByIdQuery.cs, VideoAPI/VideoApi.Events/Handlers/Core/EventHandlerBase.cs, VideoAPI/VideoApi.Events/Handlers/EndpointJoinedEventHandler.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateEndpointStatusCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Features/Callbacks.feature, VideoAPI/VideoApi.IntegrationTests/Steps/CallbacksSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/EndpointSteps.cs, VideoAPI/VideoApi.UnitTests/Events/EndpointJoinedHandlerTests.cs, VideoAPI/VideoApi.UnitTests/Events/EventHandlerFactoryTests.cs, VideoAPI/VideoApi.UnitTests/Events/EventHandlerTestBase.cs
VIH-6358
Add EndpointJoinedEventHandler
```
[ ] Yes
[x] No
```
=> VIH-6358 Add EndpointJoinedEventHandler

VideoAPI/VideoApi.AcceptanceTests/Features/Events.feature, VideoAPI/VideoApi.Events/Handlers/EndpointDisconnectedEventHandler.cs, VideoAPI/VideoApi.IntegrationTests/Features/Callbacks.feature, VideoAPI/VideoApi.IntegrationTests/Steps/CallbacksSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/EndpointSteps.cs, VideoAPI/VideoApi.UnitTests/Events/EndpointDisconnectedHandlerTests.cs, VideoAPI/VideoApi.UnitTests/Events/EventHandlerFactoryTests.cs, VideoAPI/VideoApi.UnitTests/Events/EventHandlerTestBase.cs
VIH-6539
add EndpointDisconnectedEventHandler.cs
```
[ ] Yes
[x] No
```
=> VIH-6539 add EndpointDisconnectedEventHandler.cs

VideoAPI/Testing.Common/Assertions/AssertConferenceDetailsResponse.cs, VideoAPI/Video.API/Mappings/ConferenceToDetailsResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoAPI/VideoApi.IntegrationTests/Features/Conferences.feature, VideoAPI/VideoApi.IntegrationTests/Steps/EndpointSteps.cs
VIH-6156 
* Add endpoints to ConferenceDetailsResponse.cs
```
[ ] Yes
[x] No
```
=> VIH-6156 Add endpoints to ConferenceDetailsResponse.cs

VideoAPI/VideoApi.DAL/Commands/RemoveHeartbeatsForConferencesCommand.cs
https://tools.hmcts.net/jira/browse/VIH-6444
- updated query for delete
```
[ ] Yes
[x] No
```
=> VIH-6444 fix Remove Heartbeats For Conferences Command date range

VideoAPI/VideoApi.DAL/Queries/GetExpiredAudiorecordingConferencesQuery.cs
https://tools.hmcts.net/jira/browse/VIH-6410
Delete audio app ignoring audio required flag 
```
[X ] Yes
[ ] No
```
=> VIH-6419 ignore audio recording flag to delete audio

VideoAPI/Video.API/Controllers/AudioRecordingController.cs
https://tools.hmcts.net/jira/browse/VIH-6385
=> VIH-6385 Fix the swagger definition

VideoAPI/VideoApi.DAL/Mappings/EndpointMap.cs, VideoAPI/VideoApi.DAL/Migrations/20200910104304_AddDefenceAdvocateToEndpoint.Designer.cs, VideoAPI/VideoApi.DAL/Migrations/20200910104304_AddDefenceAdvocateToEndpoint.cs, VideoAPI/VideoApi.Domain/Endpoint.cs, VideoAPI/VideoApi.UnitTests/Domain/Endpoints/AssignDefenceAdvocateTests.cs
VIH-6460
add defence advocate to endpoint
```
[ ] Yes
[x] No
```
=> VIH-6460 add defence advocate to endpoint

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Testing.Common/Helper/Builders/Api/BookNewConferenceRequestBuilder.cs, VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Controllers/EndpointsController.cs, VideoAPI/Video.API/Mappings/EndpointToResponseMapper.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/EndPointsSteps.cs, VideoAPI/VideoApi.Contract/Requests/AddEndpointRequest.cs, VideoAPI/VideoApi.Contract/Requests/UpdateEndpointRequest.cs, VideoAPI/VideoApi.Contract/Responses/EndpointResponse.cs, VideoAPI/VideoApi.DAL/Commands/AddEndpointCommand.cs, VideoAPI/VideoApi.DAL/Commands/UpdateEndpointCommand.cs, VideoAPI/VideoApi.Domain/Endpoint.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/AddEndpointCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/CreateConferenceCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateEndpointCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/EndpointSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Controllers/Endpoints/EndpointControllerTests.cs, VideoAPI/VideoApi.UnitTests/Domain/Conference/AddEndpointTests.cs, VideoAPI/VideoApi.UnitTests/Domain/Conference/RemoveEndpointTests.cs, VideoAPI/VideoApi.UnitTests/Domain/Endpoints/AssignDefenceAdvocateTests.cs, VideoAPI/VideoApi.UnitTests/Domain/Endpoints/UpdateDisplayNameTests.cs, VideoAPI/VideoApi.UnitTests/Domain/Endpoints/UpdateStatusTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/EndpointToResponseMapperTests.cs, VideoAPI/VideoApi.UnitTests/Validation/AddEndpointRequestValidationTests.cs
VIH-6461
* Can assign defence advocate when updating an endpoint
```
[ ] Yes
[x] No
```
=> VIH-6461 Assign defence advocate when updating an endpoint

VideoAPI/Testing.Common/Configuration/CvpGetAudioFileParameters.cs, VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/AudioRecordingController.cs, VideoAPI/VideoApi.IntegrationTests/Features/AudioRecording.feature, VideoAPI/VideoApi.IntegrationTests/Steps/AudioRecordingSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs
https://tools.hmcts.net/jira/browse/VIH-6506
=> VIH-6506 Update cloud room name

VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.UnitTests/Services/KinlyPlatformServiceTests.cs
VIH-6241
support endpoints when closing private consultations
```
[ ] Yes
[x] No
```
=> VIH-6241 support endpoints when closing private consultations

VideoAPI/Video.API/ConfigureServicesExtensions.cs, VideoAPI/Video.API/Controllers/HealthCheckController.cs, VideoAPI/VideoApi.Common/Configuration/WowzaConfiguration.cs, VideoAPI/VideoApi.IntegrationTests/appsettings.json, VideoAPI/VideoApi.Services/AudioPlatformService.cs, VideoAPI/VideoApi.Services/AudioPlatformServiceStub.cs, VideoAPI/VideoApi.Services/Contracts/IAudioPlatformService.cs, VideoAPI/VideoApi.UnitTests/Controllers/HealthChecks/HealthTests.cs, VideoAPI/VideoApi.UnitTests/Services/AudioPlatformServiceTest.cs, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-6051
=> VIH-6051 Multiple wowza nodes

VideoAPI/Video.API/Controllers/ConferenceManagementController.cs, VideoAPI/Video.API/Mappings/HearingLayoutMapper.cs, VideoAPI/Video.API/ValidationMiddleware/RequestModelValidatorService.cs, VideoAPI/Video.API/Validations/StartHearingRequestValidation.cs, VideoAPI/VideoApi.Contract/Requests/StartHearingRequest.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceManagementSteps.cs, VideoAPI/VideoApi.Services.Generator/kinly-swagger.json, VideoAPI/VideoApi.Services/Clients/KinlyApiClient.cs, VideoAPI/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs, VideoAPI/VideoApi.UnitTests/Mappings/HearingLayoutMapperTests.cs, VideoAPI/VideoApi.UnitTests/Middleware/RequestModelValidatorServiceTests.cs, VideoAPI/VideoApi.UnitTests/Services/KinlyPlatformServiceTests.cs, VideoAPI/VideoApi.UnitTests/Validation/StartHearingRequestValidationTests.cs
VIH-6432
Supply hearing layout on start
```
[x] Yes
[ ] No
```
=> VIH-6432 Supply hearing layout on start

VideoAPI/VideoApi.Services/Clients/WowzaHttpClient.cs
https://tools.hmcts.net/jira/browse/VIH-6232
=> VIH-6232 add wowza module

VideoAPI/Video.API/ConfigureServicesExtensions.cs, VideoAPI/Video.API/Controllers/HealthCheckController.cs, VideoAPI/VideoApi.AcceptanceTests/Features/HealthCheck.feature, VideoAPI/VideoApi.Services.Generator/kinly-swagger.json, VideoAPI/VideoApi.Services/Clients/KinlyApiClient.cs, VideoAPI/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Controllers/HealthChecks/HealthTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetTestCallResultForParticipantTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/GetTestCallResultForRepresentativeTest.cs, VideoAPI/VideoApi.UnitTests/Validation/StartHearingRequestValidationTests.cs
VIH-6255
* use kinly health check endpoint
* reduce retry attempts for test score endpoint to speed up response time
```
[ ] Yes
[x] No
```
=> VIH-6255 use kinly health check endpoint

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/AudioRecordingController.cs, VideoAPI/VideoApi.IntegrationTests/Features/AudioRecording.feature, VideoAPI/VideoApi.IntegrationTests/Steps/AudioRecordingSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs
https://tools.hmcts.net/jira/browse/VIH-6602
=> VIH-6602 cvp parameters change

VideoAPI/Testing.Common/Assertions/AssertParticipantForJudgeResponse.cs, VideoAPI/Video.API/Mappings/ConferenceForJudgeResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceForJudgeResponse.cs, VideoAPI/VideoApi.UnitTests/Mappings/ParticipantForJudgeResponseMapperTests.cs
VIH-6621
add hearing role to judge summary response
```
[ ] Yes
[x] No
```
=> VIH-6621 add hearing role to judge summary response

VideoAPI/Video.API/Controllers/AudioRecordingController.cs, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs
https://tools.hmcts.net/jira/browse/VIH-6644
do not raise the error if audio blob file not found for conference that not required audio recording
```
[X] Yes
[ ] No
```
=> VIH-6644 check audio required flag when looking for a blob file

VideoAPI/VideoApi.AcceptanceTests/Features/Events.feature, VideoAPI/VideoApi.Domain/Enums/EventType.cs, VideoAPI/VideoApi.Events/Handlers/ConnectingToConferenceEventHandler.cs, VideoAPI/VideoApi.Events/Handlers/ConnectingToEventHubEventHandler.cs, VideoAPI/VideoApi.Events/Handlers/SelectingMediaEventHandler.cs, VideoAPI/VideoApi.IntegrationTests/Features/Callbacks.feature, VideoAPI/VideoApi.UnitTests/Events/EventHandlerFactoryTests.cs, VideoAPI/VideoApi.UnitTests/Events/EventHandlerTestBase.cs
VIH-6655
Added the following event types:
ConnectingToEventHub
SelectingMedia
ConnectingToConference
```
[ ] Yes
[x] No
```
=> VIH-6655 add new events

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceManagementController.cs, VideoAPI/Video.API/Validations/TransferParticipantRequestValidation.cs, VideoAPI/Video.API/appsettings.Development.json, VideoAPI/VideoApi.Contract/Requests/TransferParticipantRequest.cs, VideoAPI/VideoApi.IntegrationTests/Features/ConferenceManagement.feature, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceManagementSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/ConferenceManagement/TransferParticipantTests.cs, VideoAPI/VideoApi.UnitTests/Validation/TransferParticipantRequestValidationTests.cs
VIH-6235
* Allow participants to be transferred in or out of hearing rooms
```
[ ] Yes
[x] No
```
=> VIH-6235 Allow participants to be transferred in or out of hearing rooms

VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceManagementSteps.cs
VIH-6235
* Fix test setup
```
[ ] Yes
[x] No
```
=> VIH-6235 Fix test setup

VideoAPI/Testing.Common/Assertions/AssertParticipantSummaryResponse.cs
- Help identify Prod null response issue
```
[ ] Yes
[X] No
```
=> VIH-5255 Help identify Prod null response issue

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceManagementController.cs, VideoAPI/VideoApi.IntegrationTests/Features/ConferenceManagement.feature, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceManagementSteps.cs, VideoAPI/VideoApi.Services.Generator/kinly-swagger.json, VideoAPI/VideoApi.Services/Clients/KinlyApiClient.cs, VideoAPI/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformService.cs, VideoAPI/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoAPI/VideoApi.UnitTests/Controllers/ConferenceManagement/SuspendVideoHearingTests.cs, VideoAPI/VideoApi.UnitTests/Services/KinlyPlatformServiceTests.cs
VIH-6731
reintroduce ability to suspend a hearing
```
[ ] Yes
[x] No
```
=> VIH-6731 reintroduce ability to suspend a hearing

VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/TasksController.cs, VideoAPI/Video.API/Validations/AddTaskRequestValidation.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.Contract/Requests/AddTaskRequest.cs, VideoAPI/VideoApi.DAL/Commands/AddTaskCommand.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/AddTaskCommandTests.cs, VideoAPI/VideoApi.IntegrationTests/Features/Tasks.feature, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/TaskSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/Tasks/TasksControllerTests.cs, VideoAPI/VideoApi.UnitTests/Validation/AddTaskRequestValidationTests.cs
https://tools.hmcts.net/jira/browse/VIH-6672
- added endpoint to add a task (alert) for a participant in a conference
```
[ ] Yes
[x] No
```
=> VIH-6672 VHO_sees_Witness_dismissed_alert 

VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/CloseConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs
https://tools.hmcts.net/jira/browse/VIH-6755
check Actual start time of the conference when delete audio app, and use factory to create blob storage service
```
[ X] Yes
[ ] No
```
=> VIH-6755 Fix audio recording false positives

VideoAPI/Testing.Common/Assertions/AssertConferenceForAdminResponse.cs, VideoAPI/Video.API/Mappings/ConferenceForAdminResponseMapper.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceForAdminResponse.cs
VIH-6590 
Added telephoneconferenceid to admin response
```
[ ] Yes
[x] No
```
=> VIH-6590 added telephoneconferenceid to admin response

VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/BookNewConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs
https://tools.hmcts.net/jira/browse/VIH-6711
=> VIH-6711 Create conference retries

VideoAPI/Video.API/Controllers/AudioRecordingController.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/VideoApi.Services/AzureStorageServiceBase.cs, VideoAPI/VideoApi.Services/Contracts/IAzureStorageService.cs, VideoAPI/VideoApi.Services/CvpAzureStorageService.cs, VideoAPI/VideoApi.Services/VhAzureStorageService.cs, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/CloseConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Services/CvpAzureStorageServiceTest.cs, VideoAPI/VideoApi.UnitTests/Services/VhAzureStorageServiceTest.cs
https://tools.hmcts.net/jira/browse/VIH-6846
on Close hearing search by prefix for audio files in Blob
```
[ X] Yes
[ ] No
```
=> VIH-6846 search for multi audio files in Blob

VideoAPI/Video.API/Factories/AzureStorageServiceFactory.cs, VideoAPI/VideoApi.Common/Configuration/CvpConfiguration.cs, VideoAPI/VideoApi.Common/Configuration/IBlobStorageConfiguration.cs, VideoAPI/VideoApi.Common/Configuration/WowzaConfiguration.cs, VideoAPI/VideoApi.Services/AzureStorageServiceBase.cs, VideoAPI/VideoApi.Services/Contracts/IAzureStorageService.cs, VideoAPI/VideoApi.Services/CvpAzureStorageService.cs, VideoAPI/VideoApi.Services/VhAzureStorageService.cs, VideoAPI/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/CloseConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Factories/AzureStorageServiceFactoryTests.cs
VIH-6846
A little refactoring
```
[ ] Yes
[X] No
```
=> VIH-6846 Refactoring

VideoAPI/Testing.Common/Assertions/AssertConferenceForAdminResponse.cs, VideoAPI/Testing.Common/Helper/ApiUriFactory.cs, VideoAPI/Video.API/Controllers/ConferenceController.cs, VideoAPI/Video.API/Mappings/ConferenceForAdminResponseMapper.cs, VideoAPI/Video.API/Startup.cs, VideoAPI/VideoApi.Common/Security/Kinly/KinlyConfiguration.cs, VideoAPI/VideoApi.Contract/Responses/ConferenceForAdminResponse.cs, VideoAPI/VideoApi.DAL/Queries/GetConferencesForTodayByIndividualQuery.cs, VideoAPI/VideoApi.IntegrationTests/Features/ConferencesToday.feature, VideoAPI/VideoApi.IntegrationTests/Helper/TestDataManager.cs, VideoAPI/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoAPI/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/BookNewConferenceTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTestBase.cs, VideoAPI/VideoApi.UnitTests/Mappings/ConferenceForAdminResponseMapperTests.cs, azure-pipelines.yml
VIH-6590
Return the conference phone number for Admins
```
[ ] Yes
[x] No
```
=> VIH-6590 Return the conference phone number for Admins

VideoAPI/Testing.Common/Assertions/AssertConferenceForAdminResponse.cs
- Ignore null telephone conference ids
```
[ ] Yes
[X] No
```
=> VIH-5255 Ignore null telephone conference ids

VideoAPI/Testing.Common/Configuration/Test.cs, VideoAPI/VideoApi.AcceptanceTests/Features/AudioRecording.feature, VideoAPI/VideoApi.AcceptanceTests/Features/Conference.feature, VideoAPI/VideoApi.AcceptanceTests/Hooks/RemoveDataHooks.cs, VideoAPI/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoAPI/VideoApi.AcceptanceTests/parameters.runsettings
- VIH-5255 Improvements for VHO conferences today test
```
[ ] Yes
[X] No
```
=> VIH-5255 Improvements for VHO conferences today test

VideoAPI/VideoApi.DAL/Queries/GetNonClosedConferenceByHearingRefIdQuery.cs
https://tools.hmcts.net/jira/browse/VIH-6859
Fixed missing JVS endpoints
```
[ ] Yes
[x ] No
```
=> VIH-6859 Fixed the missing endpoints

VideoAPI/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoAPI/Video.API/Mappings/MeetingRoomToResponseMapper.cs, VideoAPI/VideoApi.Domain/MeetingRoom.cs, VideoAPI/VideoApi.UnitTests/Domain/MeetingRoom/IsSetTests.cs
VIH-6914
return meeting room without telephone conference
```
[ ] Yes
[X] No
```
=> VIH-6914 return meeting room without telephone conference

VideoAPI/VideoApi.DAL/Queries/GetNonClosedConferenceByHearingRefIdQuery.cs, VideoAPI/VideoApi.IntegrationTests/Database/Queries/GetNonClosedConferenceByHearingRefIdQueryTests.cs
https://tools.hmcts.net/jira/browse/VIH-6859
Integration tests for missing endpoints
```
[ ] Yes
[ ] No
```
=> VIH-6859 Integration tests for missing endpoints

VideoAPI/VideoApi.Services.Generator/kinly-api.nswag, VideoAPI/VideoApi.Services.Generator/kinly-swagger.json, VideoAPI/VideoApi.Services/Clients/KinlyApiClient.cs
VIH-6523
* Update Kinly API client to enable the creation of consultation rooms
* Remove non-async methods from Kinly API Client
```
[ ] Yes
[x] No
```
=> VIH-6523 Update Kinly API client to create consultaiton rooms

VideoAPI/Video.API/Controllers/ConsultationController.cs, VideoAPI/Video.API/Services/ConsultationService.cs, VideoAPI/Video.API/Services/ConsultationServiceStub.cs, VideoAPI/VideoApi.Services/Contracts/IConsultationService.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/LeaveConsultationTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Consultation/StartConsultationRequestTests.cs, VideoAPI/VideoApi.UnitTests/Services/Consultation/ConsultationServiceTests.cs
VIH-6523
* Rename and refactor consultation service method signatures. Removes contracts as parameters. Update parameters for join and leave to be more consistent between the two.
```
[ ] Yes
[x] No
```
=> VIH-6523 Refactor consultation service

VideoAPI/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantStatusAndRoomCommandTests.cs
VIH-6524
```
[ ] Yes
[X] No
```
=> VIH-6524 not transferring

VideoAPI/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoAPI/VideoApi.UnitTests/Events/TransferEventHandlerTests.cs
VIH-7120
Support transfer from a dynamic consultation room to the hearing room
```
[ ] Yes
[x] No
```
=> VIH-7120 Update transfer event handler

VideoAPI/VideoApi.Services/KinlyPlatformService.cs
VIH-7136
Add additional check to filter current virtual rooms when non-JOH participants attempt to leave a private consultation
```
[ ] Yes
[x] No
```
=> VIH-7136 Non JOH participants unable to leave a consultation

VideoAPI/Video.API/Controllers/ParticipantsController.cs, VideoAPI/VideoApi.Contract/Requests/UpdateParticipantRequest.cs, VideoAPI/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoAPI/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantDetailsCommandTests.cs, VideoAPI/VideoApi.UnitTests/Controllers/Participant/UpdateParticipantDetailsTests.cs, VideoAPI/VideoApi.UnitTests/Validation/UpdateParticipantRequestValidationTests.cs
VIH-6162
Allow participant username to be updated if provided
```
[ ] Yes
[ ] No
```
=> VIH-6162 Allow participant username to be updated if provided

azure-pipelines.release.yml
=> VIH-2234 Update secret name due to case sensitivity

VideoApi/VideoApi.AcceptanceTests/packages.lock.json, VideoApi/VideoApi.IntegrationTests/packages.lock.json, VideoApi/VideoApi.UnitTests/packages.lock.json, VideoApi/VideoApi/Program.cs, VideoApi/VideoApi/VideoApi.csproj, VideoApi/VideoApi/packages.lock.json
VIH-7179
Add usage of AddAksKeyVaultSecretProvider()
```
[ ] Yes
[ ] No
```
=> VIH-7179 Add usage of AddAksKeyVaultSecretProvider

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Common/Helpers/LoggingDataExtractor.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoApi/VideoApi.DAL/Queries/GetNonClosedConferenceByHearingRefIdQuery.cs, VideoApi/VideoApi.IntegrationTests/Database/Queries/GetNonClosedConferenceByHearingRefIdQueryTests.cs, VideoApi/VideoApi.IntegrationTests/Steps/CallbacksSteps.cs, VideoApi/VideoApi/Controllers/ConferenceController.cs, VideoApi/VideoApi/ValidationMiddleware/RequestModelValidatorFilter.cs
VIH-6162
* Enable search for conferences by hearing ref id with a closed status
* Default to false
```
[ ] Yes
[x] No
```
=> VIH-6162 include closed conferences in get by hearing id

VideoApi/docker-compose.yml
VIH-7205
Fixing dockerfile path following the great rename
```
[ ] Yes
[X] No
```
=> VIH-7205 dockerfile path rename

VideoApi/VideoApi/Dockerfile, VideoApi/docker-compose.yml
=> VIH-7205 docker rename

VideoApi/VideoApi.Client/VideoApi.Client.csproj
VIH-7197
Update client project references
```
[ ] Yes
[x] No
```
=> VIH-7197 Update client project references

azure-pipelines.release.yml
- Added test3 env
```
[ ] Yes
[X] No
```
=> VIH-5552 Test3 Env

VideoApi/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs
VIH-7121 account for room label re-use
account for room label reuse when querying rooms during transfer events
```
[ ] Yes
[x] No
```
=> VIH-7121 Handle room label recyling

VideoApi/VideoApi/Program.cs
VIH-7179
Also load config values from vh-infra-core folder
```
[ ] Yes
[x] No
```
=> VIH-7179 Also load config values from vh-infra-core folder

VideoApi/VideoApi/Dockerfile
VIH-7179
Docker build test
https://hmctsreform.visualstudio.com/VirtualHearings/_build/results?buildId=28442&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=275f1d19-1bd8-5591-b06b-07d489ea915a
```
[ ] Yes
[X] No
```
=> VIH-7179 docker file nuget update

VideoApi/VideoApi.AcceptanceTests/Features/AudioRecording.feature, VideoApi/VideoApi.Services/AudioPlatformService.cs, VideoApi/VideoApi.Services/AudioPlatformServiceStub.cs, VideoApi/VideoApi.Services/Contracts/IAudioPlatformService.cs, VideoApi/VideoApi.UnitTests/Controllers/Conference/BookNewConferenceTests.cs, VideoApi/VideoApi.UnitTests/Services/AudioPlatformServiceTest.cs, VideoApi/VideoApi/Controllers/ConferenceController.cs
VIH-7264
Fix wowza retries. Handle 409s
If the audio app already exists, return the injest url
```
[ ] Yes
[x] No
```
=> VIH-7264 Fix wowza retries. Handle 409s

VideoApi/Testing.Common/Assertions/AssertConferenceForJudgeResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceForJudgeResponse.cs, VideoApi/VideoApi.UnitTests/Controllers/Conference/BookNewConferenceTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForJudgeResponseMapperTests.cs, VideoApi/VideoApi/Mappings/ConferenceForJudgeResponseMapper.cs
VIH-7122
include the close date time in the judge summary response
```
[ ] Yes
[x] No
```
=> VIH-7122 include the close date time in the judge summary response

VideoApi/VideoApi.Common/Configuration/SettingsConfiguration.cs, VideoApi/VideoApi/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-7254
added settings config section type and disable https setting
```
[ ] Yes
[x ] No
```
=> VIH-7254 added settings config section type and disable https setting

azure-pipelines.release.yml
- Fix for missing envs
```
[ ] Yes
[X] No
```
=> VIH-5552 Fix for missing envs

VideoApi/VideoApi.Services/Clients/WowzaHttpClient.cs
https://tools.hmcts.net/jira/browse/VIH-7295
=> VIH-7295 Change wowza stream type to live

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantStatusAndRoomCommandTests.cs, VideoApi/VideoApi.IntegrationTests/Features/Consultations/AdminConsultations.feature, VideoApi/VideoApi.IntegrationTests/Features/Consultations/RaisePrivateConsultation.feature, VideoApi/VideoApi.IntegrationTests/Features/Consultations/RespondToPrivateConsultation.feature, VideoApi/VideoApi.UnitTests/Validation/ConsultationRequestValidationTests.cs, VideoApi/VideoApi/Controllers/ConsultationController.cs, VideoApi/VideoApi/Validations/ConsultationRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-7131
VHO Calls Participant
```
[x ] Yes
[ ] No
```
=> VIH-7131 VHO Call

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Contract/Requests/EndpointConsultationRequest.cs, VideoApi/VideoApi.Contract/Responses/EndpointResponse.cs, VideoApi/VideoApi.DAL/Commands/UpdateEndpointStatusAndRoomCommand.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoApi/VideoApi.DAL/Queries/GetAvailableRoomByRoomTypeQuery.cs, VideoApi/VideoApi.DAL/Queries/GetConferenceByIdQuery.cs, VideoApi/VideoApi.DAL/Queries/GetNonClosedConferenceByHearingRefIdQuery.cs, VideoApi/VideoApi.DAL/Queries/GetRoomByIdQuery.cs, VideoApi/VideoApi.Domain/Room.cs, VideoApi/VideoApi.Events/Handlers/EndpointTransferredEventHandler.cs, VideoApi/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoApi/VideoApi.IntegrationTests/Features/Consultations/StartPrivateEndpointConsultation.feature, VideoApi/VideoApi.IntegrationTests/Steps/ConsultationSteps.cs, VideoApi/VideoApi.IntegrationTests/Steps/EndpointSteps.cs, VideoApi/VideoApi.Services/Contracts/IConsultationService.cs, VideoApi/VideoApi.UnitTests/Controllers/Consultation/HandleConsultationRequestTests.cs, VideoApi/VideoApi.UnitTests/Controllers/Consultation/RespondToConsultationRequestResponseTests.cs, VideoApi/VideoApi.UnitTests/Controllers/Consultation/StartConsultationRequestTests.cs, VideoApi/VideoApi.UnitTests/Controllers/Consultation/StartPrivateConsultationWithEndpointTests.cs, VideoApi/VideoApi.UnitTests/Events/EndpointTransferredEventHandlerTests.cs, VideoApi/VideoApi.UnitTests/Events/TransferEventHandlerTests.cs, VideoApi/VideoApi.UnitTests/Services/Consultation/ConsultationServiceTests.cs, VideoApi/VideoApi/Controllers/ConsultationController.cs, VideoApi/VideoApi/Mappings/EndpointToResponseMapper.cs, VideoApi/VideoApi/Services/ConsultationService.cs, VideoApi/VideoApi/Services/ConsultationServiceStub.cs
VIH-7094
Changed events and endpoints to support requirements
```
[ ] Yes
[X] No
```
=> VIH-7094 Changed events and endpoints to support requirements

VideoApi/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoApi/Testing.Common/Helper/Builders/Domain/MockBuildExtensions.cs, VideoApi/VideoApi.Contract/Responses/CivilianRoomResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoApi/VideoApi.DAL/Mappings/ConferenceMap.cs, VideoApi/VideoApi.DAL/Queries/GetConferenceByIdQuery.cs, VideoApi/VideoApi.Domain/Conference.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateRoomConnectionDetailsCommandTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForAdminResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs, VideoApi/VideoApi/Mappings/ConferenceToDetailsResponseMapper.cs, VideoApi/VideoApi/Mappings/RoomToCivilianRoomResponseMapper.cs
VIH-7167
* expose the civilian rooms (currently used for interpreters) so that events can be mapped to all participants in a room
```
[ ] Yes
[x] No
```
=> VIH-7167 add list of civilian rooms for a response

VideoApi/VideoApi.DAL/Commands/UpdateEndpointStatusAndRoomCommand.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoApi/VideoApi.Domain/Endpoint.cs, VideoApi/VideoApi.Domain/Participant.cs
VIH-7343
Refactoring and remove from current room
```
[ ] Yes
[X] No
```
=> VIH-7343 refactoring and remove from current room

VideoApi/VideoApi.Contract/Responses/LinkedParticipantResponse.cs, VideoApi/VideoApi.Contract/Responses/ParticipantSummaryResponse.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoApi/VideoApi.Events/Handlers/Core/EventHandlerBase.cs, VideoApi/VideoApi.Events/Handlers/JoinedEventHandler.cs, VideoApi/VideoApi.Events/Models/CallbackEvent.cs, VideoApi/VideoApi.IntegrationTests/Features/Callbacks.feature, VideoApi/VideoApi.IntegrationTests/Steps/CallbacksSteps.cs, VideoApi/VideoApi.IntegrationTests/Steps/CommonSteps.cs, VideoApi/VideoApi.UnitTests/Mappings/LinkedParticipantToResponseMapperTests.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs, VideoApi/VideoApi/Extensions/ConferenceEventRequestExtensions.cs, VideoApi/VideoApi/Mappings/EventRequestToEventCommandMapper.cs, VideoApi/VideoApi/Mappings/LinkedParticipantToResponseMapper.cs, VideoApi/VideoApi/Mappings/ParticipantToSummaryResponseMapper.cs
VIH-7167 
add and remove a participant from a VMR on join and disconnect events
```
[ ] Yes
[x] No
```
=> VIH-7167 handle VMR join and disconnect events

VideoApi/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoApi/VideoApi.UnitTests/Events/EventHandlerTestBase.cs, VideoApi/VideoApi.UnitTests/Events/TransferEventHandlerTests.cs
VIH-7395
Endpoint leaves room with defence advocate
```
[ ] Yes
[X] No
```
=> VIH-7395 - Endpoint leaves room with defence advocate

VideoApi/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoApi/VideoApi.Domain/Participant.cs, VideoApi/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoApi/VideoApi.IntegrationTests/Features/Callbacks.feature, VideoApi/VideoApi/Controllers/VideoEventsController.cs
VIH-7167
Linked participants being transferred to a hearing room get removed from the current VMR room. The transfer event handler will now keep participants within the same VMR room
```
[ ] Yes
[x] No
```
=> VIH-7167 keep participants in a VMR during transfer events

VideoApi/VideoApi.UnitTests/Mappings/ParticipantToSummaryResponseMapperTests.cs, VideoApi/VideoApi/Mappings/ParticipantToSummaryResponseMapper.cs
VIH-7001
return casetypegroup for all types
```
[ ] Yes
[X] No
```
=> VIH-7001 return casetypegroup for all types

VideoApi/VideoApi.UnitTests/Controllers/Consultation/StartPrivateConsultationWithEndpointTests.cs, VideoApi/VideoApi.UnitTests/Validation/EndpointConsultationRequestValidationTests.cs, VideoApi/VideoApi/Controllers/ConsultationController.cs, VideoApi/VideoApi/Validations/EndpointConsultationRequestValidation.cs
VIH-7403
allow vhos to call jvs endpoint
```
[ ] Yes
[x] No
```
=> VIH-7403 allow vhos to call jvs endpoint

VideoApi/VideoApi.UnitTests/Controllers/Consultation/StartPrivateConsultationWithEndpointTests.cs, VideoApi/VideoApi/Controllers/ConsultationController.cs
VHO-7403
vho can invite endpoint with no defence advocate
```
[ ] Yes
[X] No
```
=> VIH-7403 vho can invite endpoint with no defence advocate

VideoApi/VideoApi.sln
VIH-7315
Fix docker-compose.dcproj reference in main solution
```
[ ] Yes
[x] No
```
=> VIH-7315 Fix docker-compose.dcproj reference in main solution

VideoApi/VideoApi.IntegrationTests/appsettings.json, VideoApi/VideoApi.Services.Generator/kinly-swagger.json, VideoApi/VideoApi.Services/Clients/KinlyApiClient.cs, VideoApi/VideoApi.UnitTests/Services/VirtualRoom/GetOrCreateAWitnessVirtualRoomTests.cs, VideoApi/VideoApi.UnitTests/Services/VirtualRoom/GetOrCreateAnInterpreterVirtualRoomTests.cs, VideoApi/VideoApi/Services/VirtualRoomService.cs, VideoApi/VideoApi/Startup.cs, VideoApi/VideoApi/VideoApi.csproj, VideoApi/VideoApi/appsettings.Development.json, VideoApi/VideoApi/appsettings.json, VideoApi/VideoApi/nswag.json
VIH-6899
Update kinly API client when creating a participant room
```
[ ] Yes
[x] No
```
=> VIH-6899 Update kinly api client when creating a participant room

VideoApi/VideoApi.Contract/Requests/TransferParticipantRequest.cs, VideoApi/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoApi/VideoApi.Services/KinlyPlatformService.cs, VideoApi/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoApi/VideoApi.UnitTests/Controllers/ConferenceManagement/TransferParticipantTests.cs, VideoApi/VideoApi.UnitTests/Validation/TransferParticipantRequestValidationTests.cs, VideoApi/VideoApi/Controllers/ConferenceManagementController.cs, VideoApi/VideoApi/Services/ConsultationService.cs, VideoApi/VideoApi/Validations/TransferParticipantRequestValidation.cs
VIH-7194
* Update transfer request model to transfer room participants
```
[ ] Yes
[x] No
```
=> VIH-7194 support transfer of room participants

VideoApi/VideoApi/Services/VirtualRoomService.cs
VIH-7166
use tile prefix T instead of I
```
[ ] Yes
[x] No
```
=> VIH-7166 use tile prefix T instead of I

VideoApi/VideoApi.DAL/Commands/UpdateParticipantStatusAndRoomCommand.cs, VideoApi/VideoApi/Controllers/VideoEventsController.cs, VideoApi/VideoApi/Mappings/ConferenceToDetailsResponseMapper.cs
VIH-7167
handle witness join events
```
[ ] Yes
[x] No
```
=> VIH-7167 handle witness join events

VideoApi/VideoApi.Domain/Room.cs
VIH-7192
do not close witness room
```
[ ] Yes
[x] No
```
=> VIH-7192 do not close witness room

VideoApi/VideoApi.Contract/Requests/EndpointConsultationRequest.cs, VideoApi/VideoApi.IntegrationTests/Steps/ConsultationSteps.cs, VideoApi/VideoApi.UnitTests/Controllers/Consultation/StartPrivateConsultationWithEndpointTests.cs, VideoApi/VideoApi.UnitTests/Services/PollyRetryServiceTests.cs, VideoApi/VideoApi.UnitTests/Validation/EndpointConsultationRequestValidationTests.cs, VideoApi/VideoApi/Controllers/ConsultationController.cs
https://tools.hmcts.net/jira/browse/VIH-7418
Judge's invitation to endpoints
```
[X] Yes
[ ] No
```
=> VIH-7418 Judge invitation to endpoints

VideoApi/VideoApi.AcceptanceTests/Hooks/HealthcheckHooks.cs
- add healthcheck to run before AC scenario
```
[ ] Yes
[X] No
```
=> VIH-5552 Added healthcheck before AC scenarios

VideoApi/VideoApi.Contract/Responses/ConferenceForJudgeResponse.cs, VideoApi/VideoApi/Mappings/ConferenceForJudgeResponseMapper.cs
https://tools.hmcts.net/jira/browse/VIH-7367
Add participant id to judge participant response
```
[ X] Yes
[ ] No
```
=> VIH-7367 Add participant id to judge response

VideoApi/VideoApi.UnitTests/Services/Consultation/ConsultationServiceTests.cs, VideoApi/VideoApi/Services/ConsultationService.cs
VIH-7422
* use the participant room id on leave consultation if the participant is in an interpreter room
```
[ ] Yes
[x] No
```
=> VIH-7422 linked participants leave a consultatation

VideoApi/VideoApi/Controllers/ConsultationController.cs
VIH-7417 
* update display name for the event when a room participant is transferred
```
[ ] Yes
[x] No
```
=> VIH-7417 use correct display name in reason 

VideoApi/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoApi/VideoApi.Events/Handlers/RoomParticipantDisconnectedEventHandler.cs, VideoApi/VideoApi.UnitTests/Events/EventHandlerTestBase.cs, VideoApi/VideoApi.UnitTests/Events/RoomParticipantDisconnectedEventHandlerTests.cs
VIH-7402
return interpreter room back to the waiting room when a participant disconnects mid consultation
```
[ ] Yes
[x] No
```
=> VIH-7402 room participant disconnects during consultation

VideoApi/VideoApi.Domain/Participant.cs, VideoApi/VideoApi.Domain/Room.cs, VideoApi/VideoApi.Events/Handlers/CountdownFinishedEventHandler.cs, VideoApi/VideoApi.UnitTests/Controllers/VideoEvents/PostEventTests.cs, VideoApi/VideoApi.UnitTests/Events/CountdownFinishedEventHandlerTests.cs, VideoApi/VideoApi/Extensions/ConferenceEventRequestExtensions.cs
VIH-7453
move witnesses in consultation back to the waiting room when countdown is finished
```
[ ] Yes
[x] No
```
=> VIH-7453 move witnesses back to waiting room on countdown finished

VideoApi/VideoApi.Services.Generator/kinly-swagger.json, VideoApi/VideoApi.Services/Clients/KinlyApiClient.cs, VideoApi/VideoApi/Services/VirtualRoomService.cs
https://tools.hmcts.net/jira/browse/VIH-7514
Unnecessary property for Kinly Integration Video API
```
[ ] Yes
[x] No
```
=> VIH-7514 - displayname Tile names - Remove unnecessary property

VideoApi/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoApi/VideoApi.DAL/Queries/GetConsultationRoomByIdQuery.cs, VideoApi/VideoApi.UnitTests/Services/Consultation/ConsultationServiceTests.cs, VideoApi/VideoApi.UnitTests/Services/Consultation/LeaveConsultationTests.cs, VideoApi/VideoApi/Services/ConsultationService.cs
VIH-7597
* When a participant leaves a consultation and the remaining participants are two linked participants, then they are removed from a consultation also
```
[ ] Yes
[x] No
```
=> VIH-7597 room participants alone in consultation

VideoApi/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs
N/A
Ensure linked participants are in the response DTO when creating a conference with linked participants
```
[ ] Yes
[x] No
```
=> VIH-7597 Update create conference assertion

VideoApi/VideoApi/Controllers/ParticipantsController.cs, VideoApi/VideoApi/Services/VirtualRoomService.cs
https://tools.hmcts.net/jira/browse/VIH-7620
Amending the ingestion URL to distinguish interpreter VMR
```
[ ] Yes
[ X] No
```
=> VIH-7620 Amending the ingestion URL for Interpreter VMR

VideoApi/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoApi/VideoApi.UnitTests/Services/VirtualRoom/GetOrCreateAJudicialVirtualRoom.cs, VideoApi/VideoApi.UnitTests/Services/VirtualRoom/GetOrCreateAWitnessVirtualRoomTests.cs, VideoApi/VideoApi.UnitTests/Services/VirtualRoom/GetOrCreateAnInterpreterVirtualRoomTests.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs, VideoApi/VideoApi/Services/VirtualRoomService.cs, VideoApi/VideoApi/Services/VirtualRoomServiceStub.cs
https://tools.hmcts.net/jira/browse/VIH-7620
Finalise the Kinly Ingest URL format for the Interpreter VMR
```
[ ] Yes
[ ] No
```
=> VIH-7620 amend ingest url

VideoApi/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoApi/VideoApi.Domain/Participant.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantDetailsCommandTests.cs, VideoApi/VideoApi.UnitTests/Domain/Participants/LinkedParticipantTests.cs, VideoApi/VideoApi.UnitTests/Services/Consultation/LeaveConsultationTests.cs
VIH-7726
When creating LinkedParticipant entry also creates corresponding record, same as BookingsApi.
```
[ ] Yes
[x] No
```
=> VIH-7726 adding corresponding link when updating participant details

VideoApi/VideoApi.Services.Generator/kinly-swagger.json, VideoApi/VideoApi.Services/Clients/KinlyApiClient.cs
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/VIH-7758
Change description
Updated Kinly API client spec.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> VIH-7758 Update kinly api spec for create consultation request

azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7660
```
[ ] Yes
[X] No
```
=> VIH-7660 - updated PAT

VideoApi/VideoApi.Contract/Requests/UpdateConferenceParticipantsRequest.cs, VideoApi/VideoApi.Contract/Requests/UpdateParticipantRequest.cs, VideoApi/VideoApi.DAL/Commands/RemoveInstantMessagesForConferenceCommand.cs, VideoApi/VideoApi.DAL/Commands/UpdateConferenceParticipantsCommand.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoApi/VideoApi.Domain/Conference.cs, VideoApi/VideoApi.Domain/Participant.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateConferenceParticipantsCommandTests.cs, VideoApi/VideoApi.UnitTests/Controllers/Participant/UpdateConferenceParticipantsTests.cs, VideoApi/VideoApi.UnitTests/Validation/UpdateConferenceParticipantsRequestValidationTests.cs, VideoApi/VideoApi/Controllers/ConferenceController.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs, VideoApi/VideoApi/Validations/UpdateConferenceParticipantsRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-7766
Created a new endpoint and command which is responsible for updating a conference's participants.
```
[ ] Yes
[ x ] No
```
=> VIH-7766 Create Endpoint which takes in a full list of participants and updates the conference with them

VideoApi/VideoApi.Domain/Enums/UserRole.cs
https://tools.hmcts.net/jira/browse/VIH-8036
Add Staff Member to contract enums ( VideoApi.Client)
```
[ ] Yes
[x] No
```
=> VIH-8036 VHO confirms booking with Staff Member

VideoApi/VideoApi.UnitTests/Validation/AddQuickLinkParticipantRequestValidationTests.cs, VideoApi/VideoApi/Validations/AddQuickLinkParticipantRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-8181
Added Participant Quick-link Name validation (back-end) for special chars
Unit Test updated
```
[ ] Yes
[x] No
```
=> VIH-8181 Quick Link participant name Special Char validation

VideoApi/VideoApi.UnitTests/Controllers/ConferenceManagement/TransferParticipantTests.cs, VideoApi/VideoApi/Controllers/ConferenceManagementController.cs
https://tools.hmcts.net/jira/browse/VIH-8213
- updated logic to handle quick link user being in consultation room when being transferred to hearing
```
[ ] Yes
[x] No
```
=> VIH-8213 added logic to handle participant transfer from room type

VideoApi/VideoApi.UnitTests/Validation/AddQuickLinkParticipantRequestValidationTests.cs, VideoApi/VideoApi/Validations/AddQuickLinkParticipantRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-8181
- added missing special cases for validation
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> VIH-8181 updated tests to check for missing special cases

VideoApi/VideoApi.Contract/Consts/HearingVenueNames.cs, VideoApi/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceForHostResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceForIndividualResponse.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForHostResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForIndividualResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForJudgeResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs, VideoApi/VideoApi/Extensions/HearingVenue.cs, VideoApi/VideoApi/Mappings/ConferenceForHostResponseMapper.cs, VideoApi/VideoApi/Mappings/ConferenceForIndividualResponseMapper.cs, VideoApi/VideoApi/Mappings/ConferenceToDetailsResponseMapper.cs, VideoApi/VideoApi/VideoApi.csproj
https://tools.hmcts.net/jira/browse/VIH-7768
- updating contract response to include scottish venue flag that will be used by video web to switch logos
```
[ ] Yes
[x] No
```
=> VIH-7768 adding hearing venue to required responses

VideoApi/VideoApi.UnitTests/Controllers/ConferenceManagement/TransferParticipantTests.cs, VideoApi/VideoApi/Controllers/ConferenceManagementController.cs
[VIH-8380](https://tools.hmcts.net/jira/browse/VIH-8380)
- Changed method so it will transfer dual host from wherever they are not just waiting room.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> VIH-8380 staff member judge joins hearing from consultation room

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Contract/Requests/ConferenceForStaffMembertWithSelectedVenueRequest.cs, VideoApi/VideoApi.DAL/Queries/GetConferencesTodayForStaffMemberByHearingVenueNameQuery.cs, VideoApi/VideoApi.UnitTests/Controllers/Conference/GetConferenceByHearingVenueNameForStaffMemberTests.cs, VideoApi/VideoApi.UnitTests/DAL/Queries/GetConferencesTodayForStaffMemberByHearingVenueNameQueryHandlerTests.cs, VideoApi/VideoApi.UnitTests/Validation/ConferenceForHostWithSelectedVenueRequestValidationTests.cs, VideoApi/VideoApi/Controllers/ConferenceController.cs, VideoApi/VideoApi/Validations/ConferenceForHostWithSelectedVenueRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-8438
- created new endpoint to be  consumed for staff member request with hearing venue names
```
[ ] Yes
[x] No
```
=> VIH-8438 added new endpoint to fetch todays conferences for staff member

VideoApi/VideoApi.Services/KinlyPlatformService.cs, VideoApi/VideoApi.Services/KinlyPlatformServiceStub.cs, VideoApi/VideoApi/Controllers/ConferenceManagementController.cs
https://tools.hmcts.net/jira/browse/VIH-8472
=> VIH-8472 Remote lock is turned off by default when starting a hearing

VideoApi/VideoApi.DAL/Commands/UpdateConferenceParticipantsCommand.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateConferenceParticipantsCommandTests.cs
https://tools.hmcts.net/jira/browse/VIH-8508
- Remove participants from the existing participants which are in the list of removed participants.
```
[ ] Yes
[x] No
```
=> VIH-8508 Update existing participant

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Contract/Responses/AddStaffMemberResponse.cs, VideoApi/VideoApi.UnitTests/Controllers/Participant/AddStaffMemberToConferenceTests.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-8571
- Updated the controlled to return Ok result with participant details
- Added New Staff member Response model to the contract
```
[x] Yes
[ ] No
```
=> VIH-8571 Update the response type when adding a staffmember 

VideoApi/Testing.Common/Assertions/AssertConferenceForAdminResponse.cs, VideoApi/VideoApi.Client/VideoApi.Client.csproj, VideoApi/VideoApi.Common/Security/Kinly/KinlyConfiguration.cs, VideoApi/VideoApi.Contract/Responses/ConferenceForAdminResponse.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForAdminResponseMapperTests.cs, VideoApi/VideoApi/Mappings/ConferenceForAdminResponseMapper.cs, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8435
=> VIH-8435 Welsh conference numbers are now returned via the api

VideoApi/VideoApi.Contract/Consts/HearingVenueNames.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForHostResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForIndividualResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs, VideoApi/VideoApi/Extensions/HearingVenue.cs
VIH-8553
new Hearing Venue
```
[ ] Yes
[x] No
```
=> VIH-8553 New  Hearing Venue Ayr

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi/Controllers/ConferenceController.cs, VideoApi/VideoApi/VideoApi.csproj, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8547
```
[ ] Yes
[ x] No
```
=> VIH-8547 committing missing file from orginal brach.

azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8732
```
[ ] Yes
[X] No
```
=> VIH-8732 Repoint-dotnet-cvp-test-to-stg

VideoApi/VideoApi.Common/Security/QuickLinksJwtTokenProvider.cs
https://tools.hmcts.net/jira/browse/VIH-8721
- VH Claims priority over Microsoft Identity 
```
[ ] Yes
[x] No
```
=> VIH-8721 Fixed adding QL participants multiple times because of claims

VideoApi/VideoApi.UnitTests/Controllers/Consultation/ConsultationControllerTestBase.cs, VideoApi/VideoApi.UnitTests/Controllers/Consultation/StartPrivateConsultationWithEndpointTests.cs, VideoApi/VideoApi/Controllers/ConsultationController.cs
https://tools.hmcts.net/jira/browse/VIH-8741
=> VIH-8741 Staff member can now invite endpoints

VideoApi/VideoApi.Client/VideoApiClient.cs
VIH-8673
- fixed typo in the endpoint name generated by nswag
```
[x] Yes
[ ] No
```
=> VIH-8673 fixed typo in the endpoint name generated by nswag

VideoApi/VideoApi/Startup.cs, VideoApi/VideoApi/VideoApi.csproj, VideoApi/VideoApi/packages.lock.json, azure-pipelines.release.yml, azure-pipelines.yml
VIH-8887
Use the Pipeline to deploy EF instead of the Application
```
[ ] Yes
[ x ] No
```
=> VIH-8887 Add EF publishing

azure-pipelines.release.yml, azure-pipelines.yml
Add the missing wowza vars for the app settings
```
[ ] Yes
[ x ] No
```
=> VIH-7947 - Add Wowza vars for the pipeline

VideoApi/VideoApi.DAL/Queries/GetConferenceByIdQuery.cs
- [ x] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[ x] No
```
=> VIH-9007 Added async and await to the query

.github/workflows/close-pr.yaml, VideoApi/VideoApi/Controllers/HealthCheckController.cs, VideoApi/nuget.sds.config, azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml, charts/vh-video-api/Chart.yaml, charts/vh-video-api/requirements.yaml, charts/vh-video-api/values.demo.template.yaml, charts/vh-video-api/values.dev.template.yaml, charts/vh-video-api/values.yaml, docker-compose.yml, sds-git-version-config.yml, variables/dev.yaml, variables/production.yaml, variables/qa.yaml, variables/shared.yaml, variables/staging.yaml
VIH-8972
SDS Migration for App
```
[ ] Yes
[ x ] No
```
=> VIH-8972 - sds migration

azure-pipelines.sds.release.yml, sds-git-version-config.yml
Add Test to DB deployment list
Update the regex for git version
```
[ ] Yes
[ x ] No
```
=> VIH-9193 - Add test DB push and update gitversion

azure-pipelines.sds.release.yml, sds-git-version-config.yml, variables/test.yaml
[VIH-9193](https://tools.hmcts.net/jira/browse/VIH-9193)
Add Test Environment
```
[ ] Yes
[ x ] No
```
=> VIH-9193 - Add Test Environment

VideoApi/VideoApi.DAL/Commands/RemoveHeartbeatsForConferencesCommand.cs, VideoApi/VideoApi.DAL/VideoApi.DAL.csproj, VideoApi/VideoApi.DAL/packages.lock.json, VideoApi/VideoApi.IntegrationTests/packages.lock.json, VideoApi/VideoApi.UnitTests/packages.lock.json, VideoApi/VideoApi/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9180
Refactored RemoveHeartbeatsForConferencesCommand.cs to use batchDelete from EntityFramework.Plus package
```
[ ] Yes
[X] No
```
=> VIH-9180 Make heartbeat deletion more efficient

charts/vh-video-api/Chart.yaml, charts/vh-video-api/values.yaml
VIH-9236
Add missing variables
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add missing variables

charts/vh-video-api/Chart.yaml, charts/vh-video-api/values.yaml
VIH-9236
Add missing config for Authority
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add missing config for Authority

charts/vh-video-api/Chart.yaml, charts/vh-video-api/values.yaml
VIH-9236
Add missing Tenant ID
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add missing Tenant ID

VideoApi/VideoApi.Common/Configuration/WowzaConfiguration.cs, VideoApi/VideoApi.Services/AudioPlatformService.cs, VideoApi/VideoApi.Services/AudioPlatformServiceStub.cs, VideoApi/VideoApi.Services/Clients/WowzaHttpClient.cs, VideoApi/VideoApi.Services/Contracts/IAudioPlatformService.cs, VideoApi/VideoApi.Services/Contracts/IWowzaHttpClient.cs, VideoApi/VideoApi.UnitTests/Controllers/HealthChecks/HealthTests.cs, VideoApi/VideoApi.UnitTests/Services/AudioPlatformServiceTest.cs, VideoApi/VideoApi/ConfigureServicesExtensions.cs, VideoApi/VideoApi/Controllers/HealthCheckController.cs, azure-pipelines.release.yml, azure-pipelines.yml, charts/vh-video-api/Chart.yaml, charts/vh-video-api/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9173
Updated health check to look specifically at Loadbalancer client. Added property to WowzaHttpClient.cs to identify loadbalancer. Updated yml kvp name of WowzaConfiguration:RestApiEndpoints to WowzaConfiguration:LoadBalancer
```
[ ] Yes
[X] No
```
=> VIH-9173 Update Wowza health check to ping load balancer

VideoApi/VideoApi.Services/Contracts/IConsultationService.cs, VideoApi/VideoApi.UnitTests/Controllers/Consultation/StartConsultationRequestTests.cs, VideoApi/VideoApi/Services/ConsultationService.cs, VideoApi/VideoApi/Services/ConsultationServiceStub.cs
https://tools.hmcts.net/jira/browse/VIH-9220
Sets private meetings/participant consultations to start locked
```
[ ] Yes
[x] No
```
=> VIH-9220 Set participant consultations to start locked

charts/vh-video-api/Chart.yaml, charts/vh-video-api/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9381
Updates the app setting names - still wrong after the previous PR!
```
[ ] Yes
[x] No
```
=> VIH-9381 Update conference phone number setting names

azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9241 - Only RUN EF if New
VIH-9241 - Only RUN EF if New
```
[ ] Yes
[ x ] No
```
=> VIH-9241 - Amend EF Logic

VideoApi/VideoApi/Dockerfile
Amend Dockerfile
```
[ ] Yes
[x ] No
```
=> VIH-9999 - Amend Dockerfile

VideoApi/VideoApi.DAL/Commands/RemoveHeartbeatsForConferencesCommand.cs, VideoApi/VideoApi.DAL/Mappings/TaskMap.cs, VideoApi/VideoApi.DAL/Migrations/20221031125011_AddIndexToConferenceIdOnTask.Designer.cs, VideoApi/VideoApi.DAL/Migrations/20221031125011_AddIndexToConferenceIdOnTask.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/RemoveHeartbeatsForConferencesCommandTests.cs, VideoApi/VideoApi.IntegrationTests/Features/Conferences.feature, VideoApi/VideoApi.IntegrationTests/Steps/ParticipantSteps.cs
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```
=> VIH-9440 fix for remove heartbeats

VideoApi/VideoApi/Program.cs
=> VIH-9467 Fix nuget package version issue

VideoApi/VideoApi/Dockerfile
https://tools.hmcts.net/jira/browse/VIH-9477
VIH-9477 Add curl to docker build
```
[ ] Yes
[X ] No
```
=> VIH-9477 Add curl to docker build

azure-pipelines.sds.release.yml, variables/demo.yaml
https://tools.hmcts.net/jira/browse/VIH-9642
HMCTS have asked for the Demo environment for VH to be recreated.
This environment is to be used strictly for Demos and will have a copy of Production releases.
Create Demo Infra via Terraform (Core & Wowza)
Amend DNS
Configure AFD
Add Flux Configuration
Amend Release Pipelines to Run EF in Demo
```
[ ] Yes
[X ] No
```
=> VIH-9642 create demo environment in sds

.github/renovate.json
https://tools.hmcts.net/jira/browse/DTSPO-12024
Limit renovate to helm manager
```
[ ] Yes
[x] No
```
=> VIH-0000 - DTSPO-12024 - Update renovate json

azure-pipelines.sds.master-release.yml
=> VIH-9999 - amend acceptance tests checks

azure-pipelines.sds.pr-release.yml
PR Workaround
```
[ ] Yes
[X] No
```
=> VIH-0000 PR Workaround

VideoApi/VideoApi.Contract/Requests/HearingDetailRequest.cs
[VIH-9841](https://tools.hmcts.net/jira/browse/VIH-9841)
changed property to DateTimeOffset
=> VIH-9841 - Update HearingDetailRequest property

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Services/AudioPlatformService.cs, VideoApi/VideoApi.Services/Contracts/IAudioPlatformService.cs, VideoApi/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoApi/VideoApi/Controllers/AudioRecordingController.cs, azure-pipelines.sds.pr-release.yml
https://tools.hmcts.net/jira/browse/VIH-9831
Added aggregate error handling, reorganised obsolete methods and added regioniong. Added descriptive comments to AudioPlatformService.cs interface. Regenerated client
```
[X] Yes
[ ] No
```
=> VIH-7969 Improving judge audio alerts

.github/CODEOWNERS
https://tools.hmcts.net/jira/browse/VIH-10016
Update so all code changes need vh and vh-qa & so that devops approve the pipeline files and the .github folder
```
[ ] Yes
[x] No
```
=> VIH-10016 update codeowner file

azure-pipelines.sds.pr-release.yml
removing pr workaround
```
[ ] Yes
[X] No
```
=> VIH-0000 removing pr workaround

VideoApi/VideoApi.Contract/Consts/HearingVenueNames.cs, VideoApi/VideoApi/Extensions/HearingVenue.cs
VIH-10115
Update Scottish venue list
Short term fix until booking list is retrieved from Bookings API
```
[ ] Yes
[x] No
```
=> VIH-10115 Update Scottish venue list

VideoApi/VideoApi.Contract/Requests/UpdateParticipantRequest.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantDetailsCommand.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantDetailsCommandTests.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-10090
- Update the user role, hearing role and case type group when updating participants so that we can modify a participant's role for the update JOH endpoint
```
[x] Yes
[ ] No
```
=> VIH-10090 Update JOH in the booking

VideoApi/Testing.Common/Assertions/AssertConferenceDetailsResponse.cs, VideoApi/Testing.Common/Assertions/AssertConferenceForAdminResponse.cs, VideoApi/Testing.Common/Assertions/AssertConferenceForIndividualResponse.cs, VideoApi/Testing.Common/Assertions/AssertConferenceForJudgeResponse.cs, VideoApi/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoApi/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceForAdminResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceForHostResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceForIndividualResponse.cs, VideoApi/VideoApi.Domain/Conference.cs, VideoApi/VideoApi.IntegrationTests/Api/Conferences/GetConferencesForHostByHearingRefIdTests.cs, VideoApi/VideoApi.UnitTests/Domain/Conference/IsConferenceAccessibleTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForHostResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForIndividualResponseMapperTests.cs, VideoApi/VideoApi/Mappings/ConferenceForAdminResponseMapper.cs, VideoApi/VideoApi/Mappings/ConferenceForHostResponseMapper.cs, VideoApi/VideoApi/Mappings/ConferenceForIndividualResponseMapper.cs, VideoApi/VideoApi/Mappings/ConferenceToDetailsResponseMapper.cs
VIH-10157
Add IsWaitingRoomAvailable to contract response models and Hearing Id
```
[ ] Yes
[x] No
```
=> VIH-10157  Update contract response models

VideoApi/VideoApi/Middleware/Logging/RequestBodyLoggingMiddleware.cs, VideoApi/VideoApi/Startup.cs
[VIH-10112](https://tools.hmcts.net/jira/browse/VIH-10112)
Add request body logging to help debug
```
[ ] Yes
[x] No
```
=> VIH-10112 Add request body logging

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.DAL/Exceptions/ParticipantNotFoundException.cs, VideoApi/VideoApi.Domain/Conference.cs, VideoApi/VideoApi.UnitTests/Controllers/Conference/GetConferencesTodayByHearingVenueNameTests.cs, VideoApi/VideoApi.UnitTests/Controllers/Participant/UpdateConferenceParticipantsTests.cs, VideoApi/VideoApi/Controllers/ConferenceController.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs, VideoApi/VideoApi/Extensions/ExceptionMiddleware.cs, VideoApi/VideoApi/Extensions/ModelStateExtensions.cs
N/A
Capture domain rule exceptions when updating participant list
```
[ ] Yes
[x] No
```
=> VIH-10174 Capture domain rule exceptions when updating participant list

azure-pipelines.sds.data.release.yml
https://tools.hmcts.net/jira/browse/VIH-10248
Adding in unlock-lock template
=> VIH-10248 Add unlock yaml

VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.UnitTests/Controllers/AudioRecording/AudioRecordingControllerTest.cs, VideoApi/VideoApi/Controllers/AudioRecordingController.cs
[VIH-10260](https://tools.hmcts.net/jira/browse/VIH-10260)
change contract to accept a string instead of guid to search audio file
=> VIH-10260 - change contract to accept a string instead of guid to search audio file

README.md
=> VIH-0000 increment git version

VideoApi/Testing.Common/Assertions/AssertSerializableError.cs, VideoApi/VideoApi.UnitTests/Controllers/Conference/ConferenceControllerTests.cs, VideoApi/VideoApi.UnitTests/Controllers/Participant/SaveParticipantHeartbeatTests.cs, VideoApi/VideoApi/Controllers/ConferenceController.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs
https://tools.hmcts.net/jira/browse/VIH-10179
Update necessary endpoints to return ValidationProblemDetails instead of BadRequest in order to match their swagger documentation
=> VIH-10179 Return ValidationProblemDetails instead of BadRequest

VideoApi/Testing.Common/Helper/ApiUriFactory.cs, VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Contract/Requests/UpdateParticipantUsernameRequest.cs, VideoApi/VideoApi.DAL/Commands/UpdateParticipantUsernameCommand.cs, VideoApi/VideoApi.Domain/ParticipantBase.cs, VideoApi/VideoApi.IntegrationTests/Api/Participants/UpdateParticipantUsernameTests.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateParticipantUsernameTests.cs, VideoApi/VideoApi.UnitTests/Domain/Participants/UpdateParticipantUsernameTests.cs, VideoApi/VideoApi.UnitTests/Validation/UpdateParticipantUsernameRequestValidationTests.cs, VideoApi/VideoApi/Controllers/ParticipantsController.cs, VideoApi/VideoApi/Validations/UpdateParticipantUsernameRequestValidation.cs
https://tools.hmcts.net/jira/browse/VIH-10390
=> VIH-10390 New endpoint for updating participant username

RefData/Directory.Packages.props, VideoApi/Directory.Packages.props
[VIH-10125](https://tools.hmcts.net/jira/browse/VIH-10125)
disable central package management
=> VIH-10125 disable central package management

VideoApi/VideoApi.DAL/Commands/CreateConsultationRoomCommand.cs, VideoApi/VideoApi.Domain/Conference.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/CreateConsultationRoomCommandTests.cs, VideoApi/VideoApi.UnitTests/Domain/Conference/AddRoomTests.cs
VIH-10711
Add domain method for adding rooms to apply domain rules. Room labels should be unique whilst another with the same label is still live
=> VIH-10711 add domain method for adding rooms to apply domain rules

VideoApi/Testing.Common/Helper/ApiUriFactory.cs, VideoApi/Testing.Common/Testing.Common.csproj, VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Common/VideoApi.Common.csproj, VideoApi/VideoApi.Common/packages.lock.json, VideoApi/VideoApi.Contract/VideoApi.Contract.csproj, VideoApi/VideoApi.DAL/Queries/GetActiveConferencesQuery.cs, VideoApi/VideoApi.DAL/VideoApi.DAL.csproj, VideoApi/VideoApi.DAL/packages.lock.json, VideoApi/VideoApi.Domain/VideoApi.Domain.csproj, VideoApi/VideoApi.Events/VideoApi.Events.csproj, VideoApi/VideoApi.IntegrationTests/Api/EndOfDays/GetActiveConferencesTests.cs, VideoApi/VideoApi.IntegrationTests/Helper/TestDataManager.cs, VideoApi/VideoApi.IntegrationTests/VideoApi.IntegrationTests.csproj, VideoApi/VideoApi.IntegrationTests/packages.lock.json, VideoApi/VideoApi.Services/VideoApi.Services.csproj, VideoApi/VideoApi.UnitTests/VideoApi.UnitTests.csproj, VideoApi/VideoApi.UnitTests/packages.lock.json, VideoApi/VideoApi/Controllers/EndOfDayController.cs, VideoApi/VideoApi/VideoApi.csproj, VideoApi/VideoApi/packages.lock.json
VIH-10723
GET operation to retrieve active sessions
=> VIH-10723 get end of day active sessions

VideoApi/VideoApi.Events/Handlers/EndpointJoinedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/JoinedEventHandler.cs, VideoApi/VideoApi.UnitTests/Events/EndpointJoinedHandlerTests.cs
VIH-10767
auto transfer endpoints who join late (i.e. hearing is already in session
=> VIH-10767 auto transfer endpoints who join late

VideoApi/VideoApi.Contract/Requests/StartHearingRequest.cs, VideoApi/VideoApi.Domain/ParticipantBase.cs, VideoApi/VideoApi.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs, VideoApi/VideoApi.UnitTests/Domain/Participants/CanAutoTransferToHearingRoomTests.cs, VideoApi/VideoApi.UnitTests/Domain/Participants/IsHostTests.cs, VideoApi/VideoApi/Controllers/ConferenceManagementController.cs
VIH-10812
do not auto transfer staff members into a hearing
=> VIH-10812 do not auto transfer staff members into a hearing

VideoApi/Testing.Common/Helper/Builders/Api/BookNewConferenceRequestBuilder.cs, VideoApi/VideoApi.AcceptanceTests/ApiTests/AcApiTest.cs, VideoApi/VideoApi.AcceptanceTests/ApiTests/InstantMessages/CreateAndRemoveInstantMessageTests.cs, VideoApi/VideoApi.AcceptanceTests/Contexts/TestContext.cs, VideoApi/VideoApi.AcceptanceTests/Hooks/ConfigHooks.cs, VideoApi/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoApi/VideoApi.AcceptanceTests/VideoApi.AcceptanceTests.csproj, VideoApi/VideoApi.AcceptanceTests/appsettings.json, VideoApi/VideoApi.AcceptanceTests/packages.lock.json, VideoApi/VideoApi.Common/Helpers/TraceCategory.cs, VideoApi/VideoApi.Common/Security/Supplier/Base/SupplierConfiguration.cs, VideoApi/VideoApi.IntegrationTests/Steps/BaseSteps.cs, VideoApi/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoApi/VideoApi.IntegrationTests/Steps/EndpointSteps.cs, VideoApi/VideoApi.Services/Clients/SupplierApiClient.cs, VideoApi/VideoApi.Services/Handlers/SupplierLoggingDelegatingHandler.cs, VideoApi/VideoApi.Services/SupplierPlatformService.cs, VideoApi/VideoApi.Services/VideoApi.Services.csproj, VideoApi/VideoApi.UnitTests/Middleware/ExceptionMiddlewareTests.cs, VideoApi/VideoApi.UnitTests/Services/SupplierLoggingDelegatingHandlerTests.cs, VideoApi/VideoApi.UnitTests/Validation/AddEndpointRequestValidationTests.cs, VideoApi/VideoApi/ConfigureServicesExtensions.cs, VideoApi/VideoApi/Extensions/ExceptionMiddleware.cs, VideoApi/VideoApi/Validations/AddEndpointRequestValidation.cs, VideoApi/VideoApi/Validations/BookNewConferenceRequestValidation.cs, VideoApi/VideoApi/appsettings.json, azure-pipelines.sds.pr-release.yml, charts/vh-video-api/Chart.yaml, charts/vh-video-api/values.yaml
VIH-10826
capture supplier exceptions in the ExceptionMiddleware.cs and log the response
=> VIH-10826 handle supplier exceptions

.github/CODEOWNERS
Adds @hmcts/vh team to code owners for azure-pipelines* path
=> VIH-0000 add hmcts vh team as codeowners to azure pipelines path

azure-pipelines.sds.master-release.yml
See [VIH-10889](https://tools.hmcts.net/jira/browse/VIH-10889)
Adds Demo env to Entity Framework stage in master release pipeline
=> VIH-10889 Adds Demo env to Entity Framework stage in master release pipeline

azure-pipelines.sds.master-release.yml
See [VIH-10889](https://tools.hmcts.net/jira/browse/VIH-10889)
Change description
Corrects errors in stage dependencies
=> VIH-10889 correct stage dependencies

VideoApi/VideoApi.Contract/Responses/ConferenceForAdminResponse.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceForAdminResponseMapperTests.cs, VideoApi/VideoApi/Mappings/ConferenceForAdminResponseMapper.cs
https://tools.hmcts.net/jira/browse/VIH-10863
=> VIH-10863 Add supplier to responses

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.release.yml, variables/ithc.yaml
See [VIH-10920](https://tools.hmcts.net/jira/browse/VIH-10920)
VIH-10920 add stage for db migrations for ithc env
=> VIH-10920 add db migrations for ithc

VideoApi/VideoApi.DAL/Mappings/ConferenceMap.cs, VideoApi/VideoApi.DAL/Mappings/TelephoneParticipantMap.cs, VideoApi/VideoApi.DAL/Migrations/20240920111250_AddTelephoneParticipantToConference.Designer.cs, VideoApi/VideoApi.DAL/Migrations/20240920111250_AddTelephoneParticipantToConference.cs, VideoApi/VideoApi.Domain/Conference.cs, VideoApi/VideoApi.Domain/Enums/TelephoneState.cs, VideoApi/VideoApi.Domain/TelephoneParticipant.cs, VideoApi/VideoApi.UnitTests/Domain/Conference/AddTelephoneParticipantTests.cs, VideoApi/VideoApi.UnitTests/Domain/Conference/RemoveTelephoneParticipantTests.cs, VideoApi/VideoApi.UnitTests/Domain/TelephoneParticipants/UpdateCurrentRoomTests.cs, VideoApi/VideoApi.UnitTests/Domain/TelephoneParticipants/UpdateStatusTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceCoreResponseMapperTests.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs
VIH-10945
Add TelephoneParticipants to the Conference
=> VIH-10945 Add TelephoneParticipants to the Conference

azure-pipelines.sds.master-release.yml, variables/dev.yaml, variables/test.yaml
See [VIH-10983](https://tools.hmcts.net/jira/browse/VIH-10983)
Refactor non-prod master release pipeline to allow separate image build & ad-hoc deploy to specific environments.
Tested that pipeline works as expected, and images are built and pushed with the relevant tag.
=> VIH-10983 refactor non-prod master deployment pipeline

VideoApi/VideoApi.Contract/Responses/ConferenceCoreResponse.cs, VideoApi/VideoApi.Contract/Responses/ConferenceDetailsResponse.cs, VideoApi/VideoApi.Contract/Responses/ParticipantResponse.cs, VideoApi/VideoApi.UnitTests/Mappings/ConferenceToDetailsResponseMapperTests.cs, VideoApi/VideoApi/Extensions/ContractExtensions.cs, VideoApi/VideoApi/Mappings/ConferenceToDetailsResponseMapper.cs, VideoApi/VideoApi/Mappings/ParticipantResponseMapper.cs
VIH-10950
add tel participants to response model
=> VIH-10950 add tel participants to response model

VideoApi/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoApi/VideoApi.Common/Helpers/ConferenceHelper.cs, VideoApi/VideoApi.DAL/Commands/UpdateMeetingRoomCommand.cs, VideoApi/VideoApi.DAL/Queries/GetConferencesByTelephoneIdQuery.cs, VideoApi/VideoApi.IntegrationTests/Database/Queries/GetConferenceByTelephoneIdQueryTests.cs, VideoApi/VideoApi.IntegrationTests/Helper/TestDataManager.cs, VideoApi/VideoApi.Services/Clients/SupplierApiClient.cs, VideoApi/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformServiceStub.cs, VideoApi/VideoApi.UnitTests/Helpers/ConferenceHelperTests.cs, VideoApi/VideoApi.UnitTests/Services/BookingServiceTests.cs, VideoApi/VideoApi.UnitTests/Services/SupplierPlatformServiceTests.cs, VideoApi/VideoApi/Services/BookingService.cs, azure-pipelines.sds.release.yml
https://tools.hmcts.net/jira/browse/VIH-10984
Created unique 8 digit telephone id, that is provided to pexip(vodafone implementation) returned in room response
=> VIH-10984 Created unique 8 digit telephone id generator

README.md, RefData/appsettings.json, VideoApi/VideoApi.DAL/appsettings.json, VideoApi/VideoApi.IntegrationTests/appsettings.json, VideoApi/VideoApi.IntegrationTests/packages.lock.json, VideoApi/VideoApi.UnitTests/packages.lock.json, VideoApi/VideoApi/Program.cs, VideoApi/VideoApi/VideoApi.csproj, VideoApi/VideoApi/appsettings.json, VideoApi/VideoApi/packages.lock.json, docker-compose.override.yml, setup-secrets.sh
VIH-10993
* reload on config change for secret by file
* Remove deprecated VH.Core.Configuration
=> VIH-10993 reload on config change for secret by file

VideoApi/VideoApi.Contract/Requests/StartHearingRequest.cs, VideoApi/VideoApi.Services/Clients/SupplierApiClient.cs, VideoApi/VideoApi.UnitTests/Mappings/HearingLayoutMapperTests.cs, VideoApi/VideoApi/Mappings/HearingLayoutMapper.cs
https://tools.hmcts.net/jira/browse/VIH-11001
=> VIH-11001 Add new layout options

VideoApi/VideoApi.AcceptanceTests/packages.lock.json, VideoApi/VideoApi.Client/VideoApi.Client.csproj, VideoApi/VideoApi.Client/VideoApiClient.cs, VideoApi/VideoApi.Client/VideoApiClientFactory.cs, VideoApi/VideoApi.Common/ApplicationLogger.cs, VideoApi/VideoApi.Common/Helpers/ApiRequestHelper.cs, VideoApi/VideoApi.Common/VideoApi.Common.csproj, VideoApi/VideoApi.Common/packages.lock.json, VideoApi/VideoApi.DAL/packages.lock.json, VideoApi/VideoApi.IntegrationTests/packages.lock.json, VideoApi/VideoApi.Services.Generator/kinly-api.nswag, VideoApi/VideoApi.Services/AudioPlatformService.cs, VideoApi/VideoApi.UnitTests/Services/AudioPlatformServiceTest.cs, VideoApi/VideoApi.UnitTests/packages.lock.json, VideoApi/VideoApi/ConfigureServicesExtensions.cs, VideoApi/VideoApi/Startup.cs, VideoApi/VideoApi/VideoApi.csproj, VideoApi/VideoApi/nswag.json, VideoApi/VideoApi/packages.lock.json
[VIH-11018](https://tools.hmcts.net/jira/browse/VIH-11018)
Checking for performance diff with system text json
=> VIH-11018 refactor to switch to system.text.json

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
enable demo image and helm buildpush
=> VIH-11181 - enable demo image buildpush

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
correct image tag ref to enable demo image and helm buildpush
=> VIH-11181 enable demo image build with approval

RefData/RefData.csproj, RefData/packages.lock.json, VideoApi/VideoApi.Contract/Requests/TransferParticipantRequest.cs, VideoApi/VideoApi.DAL/VideoApi.DAL.csproj, VideoApi/VideoApi.DAL/packages.lock.json, VideoApi/VideoApi.Events/Handlers/EndpointJoinedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/JoinedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/TelephoneJoinedEventHandler.cs, VideoApi/VideoApi.IntegrationTests/packages.lock.json, VideoApi/VideoApi.Services/Clients/SupplierApiClient.cs, VideoApi/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformServiceStub.cs, VideoApi/VideoApi.UnitTests/Controllers/ConferenceManagement/TransferParticipantTests.cs, VideoApi/VideoApi.UnitTests/Events/EndpointJoinedHandlerTests.cs, VideoApi/VideoApi.UnitTests/Events/JoinedEventHandlerTests.cs, VideoApi/VideoApi.UnitTests/Events/TelephoneJoinedHandlerTests.cs, VideoApi/VideoApi.UnitTests/Services/SupplierPlatformServiceTests.cs, VideoApi/VideoApi.UnitTests/VideoApi.UnitTests.csproj, VideoApi/VideoApi.UnitTests/packages.lock.json, VideoApi/VideoApi/Controllers/ConferenceManagementController.cs, VideoApi/VideoApi/VideoApi.csproj, VideoApi/VideoApi/packages.lock.json, variables/shared.yaml
VIH-11223
* Allow the option to provide the role when transferring a participant/endpoint in
* Upgrade vulnerable packages
=> VIH-11223 Allow the option to provide the role when transferring a participant or endpoint in

VideoApi/VideoApi.Common/BadRequestException.cs, VideoApi/VideoApi.Events/Handlers/TelephoneTransferredEventHandler.cs, VideoApi/VideoApi.Events/Handlers/TransferEventHandler.cs, VideoApi/VideoApi.Services/Contracts/IVideoPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformServiceStub.cs, VideoApi/VideoApi.UnitTests/Services/Consultation/ConsultationServiceTests.cs, VideoApi/VideoApi.UnitTests/Services/Consultation/LeaveConsultationTests.cs, VideoApi/VideoApi/Services/ConsultationService.cs
Fixed consultation service, to call Supplier service that the client directly
https://tools.hmcts.net/jira/browse/VIH-11227
=> VIH-11227 Fix for consultations not starting

VideoApi/VideoApi.Services/Clients/SupplierApiClient.cs, VideoApi/VideoApi.Services/FeatureToggles.cs, VideoApi/VideoApi.Services/FeatureTogglesStub.cs, VideoApi/VideoApi.Services/SupplierPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformServiceFactory.cs, VideoApi/VideoApi.UnitTests/Services/SupplierPlatformServiceFactoryTests.cs, VideoApi/VideoApi.UnitTests/Services/SupplierPlatformServiceTests.cs
https://tools.hmcts.net/jira/browse/VIH-11230
=> VIH-11230 Added SendTransferRolesEnabled feature flag

VideoApi/Testing.Common/Helper/Builders/Api/AddStaffMemberRequestBuilder.cs, VideoApi/Testing.Common/Helper/Builders/Api/BookNewConferenceRequestBuilder.cs, VideoApi/Testing.Common/Helper/Builders/Api/ParticipantRequestBuilder.cs, VideoApi/Testing.Common/Helper/Builders/Domain/ConferenceBuilder.cs, VideoApi/Testing.Common/Helper/Builders/Domain/ParticipantBuilder.cs, VideoApi/Testing.Common/Testing.Common.csproj, VideoApi/VideoApi.AcceptanceTests/Steps/ConferenceSteps.cs, VideoApi/VideoApi.AcceptanceTests/packages.lock.json, VideoApi/VideoApi.IntegrationTests/Database/Commands/AddInstantMessageCommandTests.cs, VideoApi/VideoApi.IntegrationTests/Database/Queries/GetDistinctJudgeListByFirstNameQueryTests.cs, VideoApi/VideoApi.IntegrationTests/Steps/ConferenceSteps.cs, VideoApi/VideoApi.IntegrationTests/Steps/EndpointSteps.cs, VideoApi/VideoApi.IntegrationTests/Steps/InstantMessageSteps.cs, VideoApi/VideoApi.IntegrationTests/packages.lock.json, VideoApi/VideoApi.UnitTests/DAL/Commands/AnonymiseParticipantWithUsernameCommandTests.cs, VideoApi/VideoApi.UnitTests/DAL/Commands/DomainModelFactoryForTests.cs, VideoApi/VideoApi.UnitTests/Domain/Conference/RemoveParticipantTests.cs, VideoApi/VideoApi.UnitTests/Validation/AddQuickLinkParticipantRequestValidationTests.cs, VideoApi/VideoApi.UnitTests/Validation/EmailValidatorTests.cs, VideoApi/VideoApi.UnitTests/Validation/ParticipantRequestValidationTests.cs, VideoApi/VideoApi.UnitTests/packages.lock.json
[VIH-11091](https://tools.hmcts.net/jira/browse/VIH-11091)
removed Faker.NetCore
=> VIH-11091 - replace Faker.NetCore with Bogus

.github/workflows/launch-darkly-find-code-refs-in-pr.yml, .github/workflows/launch-darkly-flag-sync.yml, .github/workflows/osv-scanner-pr.yml
VIH-11246
Update to the GitHub Actions:
* Switch the full LD code scan to run against master only and on a schedule
* Add the LD code scan on diff to run against PRs only
* Turn off fail on vuln for OSV scanner
=> VIH-11246 update github actions

VideoApi/VideoApi.Common/BadRequestTelemetry.cs, VideoApi/VideoApi.Events/Handlers/CountdownFinishedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/DisconnectedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/EndpointDisconnectedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/EndpointTransferredEventHandler.cs, VideoApi/VideoApi.Events/Handlers/JoinedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/ParticipantJoiningEventHandler.cs, VideoApi/VideoApi.Events/Handlers/RecordingConnectionEventHandler.cs, VideoApi/VideoApi.Events/Handlers/TelephoneDisconnectedEventHandler.cs, VideoApi/VideoApi.Events/Handlers/TelephoneTransferredEventHandler.cs
VIH-11273
Add additional logging to make it easier to search for transfers
=> VIH-11273 Add additional logging to make it easier to search for transfers

VideoApi/VideoApi.Events/Handlers/JoinedEventHandler.cs, VideoApi/VideoApi.Events/Models/CallbackEvent.cs, VideoApi/VideoApi.Services/SupplierPlatformService.cs, VideoApi/VideoApi.Services/SupplierPlatformServiceFactory.cs, VideoApi/VideoApi.UnitTests/Events/JoinedEventHandlerTests.cs, VideoApi/VideoApi.UnitTests/Services/SupplierPlatformServiceTests.cs
VIH-11273
* Add the conference role in the callback request so that clients and provide the role. 
* Video API has no knowledge of screening requirements
=> VIH-11273 add the conference role in the callback request

VideoApi/VideoApi.Common/Helpers/TraceCategory.cs, VideoApi/VideoApi.Events/Handlers/Core/EventHandlerBase.cs, VideoApi/VideoApi.IntegrationTests/Features/Callbacks.feature, VideoApi/VideoApi.IntegrationTests/Steps/CallbacksSteps.cs, VideoApi/VideoApi.UnitTests/Events/DisconnectedEventHandlerTests.cs, VideoApi/VideoApi.UnitTests/Events/EndpointDisconnectedHandlerTests.cs, VideoApi/VideoApi.UnitTests/Events/TelephoneDisconnectedHandlerTests.cs, VideoApi/VideoApi/Extensions/ExceptionMiddleware.cs
VIH-11294
capture UnexpectedEventOrderException and log it only add an API test for this scenario
=> VIH-11294 capture UnexpectedEventOrderException and log it only

VideoApi/VideoApi.Events/Handlers/Core/EventHandlerBase.cs
VIH-11294
Improve logging message my mapping status to string for participant
=> VIH-11294 map object to string for participant status

VideoApi/VideoApi.Events/Handlers/Core/EventHandlerBase.cs
VIH-11294
format timestamp with IOS8601 format to that the seconds are not rounded up
=> VIH-11294 format timestamp with IOS8601 format

VideoApi/VideoApi.Common/Helpers/ApiRequestHelper.cs, VideoApi/VideoApi.Services/Clients/ISupplierApiClient.cs, VideoApi/VideoApi.Services/Clients/Models/StartHearingRequest.cs, VideoApi/VideoApi.Services/SupplierPlatformService.cs, VideoApi/VideoApi.UnitTests/Services/Clients/SupplierApiClientTests.cs, VideoApi/VideoApi.UnitTests/Services/SupplierPlatformServiceTests.cs
VIH-11307
serialise hearing layout as SnakeCaseUpper
=> VIH-11307 serialise hearing layout as SnakeCaseUpper

azure-pipelines.sds.pr-release.yml
https://tools.hmcts.net/jira/browse/VIH-11302
=> VIH-11302 Remove references to obsolete variable groups

VideoApi/VideoApi.Events/Handlers/TransferEventHandler.cs
VIH-11366
add logging for why additional calls are made such as only endpoints left in a consultation room
=> VIH-11366 add logging to add context in transfer event handler

VideoApi/VideoApi.DAL/Commands/AddEndpointCommand.cs, VideoApi/VideoApi.DAL/Commands/UpdateEndpointCommand.cs, VideoApi/VideoApi.IntegrationTests/Database/Commands/AddEndpointCommandTests.cs
https://tools.hmcts.net/jira/browse/VIH-11380
added null coalesce for ParticipantsLinked parameter to set empty array to prevent null ref exception on loops
=> VIH-11380 JVS doesnt appear on video web waiting room page

VideoApi/VideoApi.Domain/Participant.cs, VideoApi/VideoApi.Domain/ParticipantBase.cs, VideoApi/VideoApi.Events/Handlers/CountdownFinishedEventHandler.cs, VideoApi/VideoApi.UnitTests/Controllers/ConferenceManagement/ConferenceManagementControllerTestBase.cs, VideoApi/VideoApi.UnitTests/Controllers/ConferenceManagement/StartVideoHearingTests.cs, VideoApi/VideoApi.UnitTests/Events/CountdownFinishedEventHandlerTests.cs
VIH-8926
Expert to have a similar journey to witnesses so they should not get auto transferred on start
=> VIH-8926 experts to have a similar UX as witnesses
